### ISSUE TITLE
[DOCS]: Environment Variables

### ISSUE THREAD

**Issue by stavros-k** [codeproject/CodeProject.AI-Server#1]
Hey, just added this project in TrueNAS SCALE [community catalog](https://github.com/truecharts/apps) as a Helm Chart.
It would be nice to have a small list of supported environment variables, 
so I can expose those on the installation UI in TrueNAS!

Thanks!

**Comment by ChrisMaunder** [comment]
We're more than happy to work with you on this. Just let us know the specifics of what you're after and we can ensure our docs are up to date. Note that each module included in our AI server has it's own inputs, outputs and environment variables. Our server has it's variables, and they are fixed, but the list of modules will be a changeable beast.

Just let us know what you need and we'll get on it.

**Comment by ChrisMaunder** [comment]
All settings are now documented at https://www.codeproject.com/AI/docs/api/module_settings.html
