### ISSUE TITLE
ObjectDetectionCoral and FaceProcessing missing download source

### ISSUE THREAD

**Issue by jfmennedy** [codeproject/CodeProject.AI-Server#104]
**Area of Concern**
- [x ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [x ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Unable to download module 'ObjectDetectionCoral' from https://www.codeproject.com/KB/articles/5348853/ObjectDetectionCoral-2.2.2.zip. Error: No bytes downloaded

Unable to install FaceProcessing: Unable to download module 'FaceProcessing' from https://www.codeproject.com/KB/articles/5348853/FaceProcessing-1.10.2.zip. Error: No bytes downloaded

**Expected behavior**
Please download and install the modules...

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.6.2
 - OS: [Windows 11]
 - System RAM [8Gb]

**Comment by ChrisMaunder** [comment]
This has been fixed

**Comment by jfmennedy** [comment]
Not in 2.6.2... I need to use which release?

**Comment by jfmennedy** [comment]
No docker image.. It happens on windows server 2016...

**Comment by matthewDDennis** [comment]
The files didn't get deployed to the Module Registry.
This has been fixed.
You may need to update to 2.6.4

**Comment by jfmennedy** [comment]
Hello,

when 2.6.4 for Windows will be released?

**Comment by matthewDDennis** [comment]
We have just release 2.6.5 to the beta testers and should be generally available today or tomorrow.
