### ISSUE TITLE
where i can find changelog for latest release?

### ISSUE THREAD

**Issue by onlineapps-cloud** [codeproject/CodeProject.AI-Server#107]
hi, you released new version (2.6.4), where i can find release log for this version?
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/69077240/8c973687-9a38-4369-bf60-1eb8588d5d90)
On github latest release is 2.6.2.

**Comment by SeanECP** [comment]
2.6.4 hasn't been formally released yet. There was 2.6.4 release for Ubuntu to address an issue installing modules.

**Comment by onlineapps-cloud** [comment]
> 2.6.4 hasn't been formally released yet. There was 2.6.4 release for Ubuntu to address an issue installing modules.

Are you shure? you can demonstrate screenshot from ubuntu where you have working modules?
because you have loot of errors in your installer script like, how to get nvidia-smi and cuddn version, and many lot of other bugs, so 2.6.4 have same problem.
i able to fix windows version, but linux version have to many bugs!

**Comment by onlineapps-cloud** [comment]
right now after 2 weeks of hard work, i able to run on linux, proof:
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/69077240/9c78c328-9f02-47ef-b3f6-95dfe25b25cb)

**Comment by SeanECP** [comment]
> you have loot of errors in your installer script like, how to get nvidia-smi and cuddn version, and many lot of other bugs, so 2.6.4 have same problem. i able to fix windows version, but linux version have to many bugs!

Can you please share your System Info, and the errors from the Server logs for 2.6.4?
