### ISSUE TITLE
Add blue text when upgrade module

### ISSUE THREAD

**Issue by onlineapps-cloud** [codeproject/CodeProject.AI-Server#108]
hi, when i install module, i have blue text about installing module, but when i want to upgrade existing module, i don't get this blue text
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/69077240/68e001d4-eeab-4548-88b6-55b6bccb8eba)
and i don't understand, when i click, install process started or not, if i click twice, i get popup where say that i need to wait when current operation will be finished
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/69077240/b5d2f411-7729-4717-80e8-30ba39f5fb4d)
and upgrade process starting again, so you need to add option to not permit to click again on this button, like on install module step. you missed this feature on upgrade module step.

**Comment by ChrisMaunder** [comment]
You mean the blue text like this?

![Screenshot 2024-12-04 154205](https://github.com/user-attachments/assets/a594bbd1-b36d-496c-8f14-3d709bab5108)
![Screenshot 2024-12-04 154215](https://github.com/user-attachments/assets/28564613-d3dd-4344-b3e4-c6036b08289e)

You didn't mention the version of the server you're using, but can I suggest you update to v2.9.4?
