### ISSUE TITLE
Where's the Dockerfile?

### ISSUE THREAD

**Issue by jlk** [codeproject/CodeProject.AI-Server#109]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [X] Something else

**Describe the bug**
I'm looking for a Dockerfile to build a docker image for the AI server. The images are up on Docker Hub, but there's no link to the source of those images, and I don't see a trace of a Dockerfile in the source tree for this project. 

Why am I looking for the docker image? Because I've seen the command in there before to just run the server from the CLI without needing VSCode or whatever else, but I was trying to get that without downloading a 5GB container image.

It's a little frustrating how difficult it is to work with this project that claims to make things easy for people...

**Comment by PrplHaz4** [comment]
There is definitely a lack of transparency with this project.  This related issue was previously opened and closed without any actual resolution: https://github.com/codeproject/CodeProject.AI-Server/issues/51

**Comment by SeanECP** [comment]
In the documentation, in the **CodeProject.AI in Docker** section, under the **Docker Compose** heading, are a series of options you could use for a Dockerfile.
[https://www.codeproject.com/AI/docs/install/running_in_docker.html](https://www.codeproject.com/AI/docs/install/running_in_docker.html)

**Comment by jlk** [comment]
@SeanECP - those are docker compose files, not Dockerfiles. Not of any use when it comes to building container images, unless a Dockerfile is specified within the docker-compose file.

**Comment by stevemcquaid** [comment]
Best I could find. 

https://hub.docker.com/layers/codeproject/ai-server/1.5.5.1/images/sha256-2af04df646e1ecb033858ca0b7b632023fe11794b2d4cb6b06ae867493edf0ec

**Comment by jlk** [comment]
Thx @stevemcquaid - I can get that off `docker history` as I'm sure you know. Alas it's missing the base image.

I'm super busy, but when I get time I'll reverse engineer this and share it out. The overall build process for this project...has room to improve.

**Comment by ChrisMaunder** [comment]
@jlk Happy to have contributions.

https://github.com/codeproject/CodeProject.AI-Server-Installers
