### ISSUE TITLE
CPAI docker without YOLOv5 6.2 and Face Processing automatically installing with docker?

### ISSUE THREAD

**Issue by m411b** [codeproject/CodeProject.AI-Server#116]
Is there a way to do this? The reason I ask, I want to use YOLOv8. But if YOLOv5 6.2 or Face Processing were previously installed, YOLOv8 fails. This behavior can also be observed on the Windows installer. I'm using docker for this on Unraid and don't want YOLOv5 6.2 or Face Processing installed automatically.

Thanks so much

**Comment by ChrisMaunder** [comment]
Unfortunately not at the moment
