### ISSUE TITLE
When no face are found, server is write an error message to log

### ISSUE THREAD

**Issue by elad-bar** [codeproject/CodeProject.AI-Server#12]
**Description**
When no face are found, server is write an error message to log

**Expected**
When no face are found (which is a normal result), log level should be informational with successful output

**Actual**
Log level is set to an error and response is a failure.

**Suggested Solution**
Instead of the following code in `src/AnalysisLayer/Vision/intelligencelayer/face.py`
```python
if found_face == False:
            output = {"success": False, "error": "No face found in image"}
```

change to:
```python
if found_face == False:
            output = {"success": True, "predictions": [], "message": "No face found in image"}
```

**Comment by ChrisMaunder** [comment]
Good catch. Done.

**Comment by elad-bar** [comment]
Reopeining the issue as in latest version, for each processing without face the following Error appear:
`Error Face Processing: No face found in image`
