### ISSUE TITLE
after installing YOLOv8 module all modules cannot work with gpu 

### ISSUE THREAD

**Issue by motogon** [codeproject/CodeProject.AI-Server#121]
**Area of Concern**
- [ Server version:   2.6.5 ] Server 
- [Object Detection (YOLOv8) ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ Docker ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [  ] Something else
- 
<img width="1540" alt="image" src="https://github.com/user-attachments/assets/d16dba08-fff5-45ab-8145-339563a2406d">

**Describe the bug**

Immediately after creating the container : 
docker run --name CodeProject.AI -d -p 33168:32168 --gpus all \
 --privileged
 --restart=unless-stopped.
 --device /dev/bus/usb:/dev/bus/usb.
 --shm-size=164m.
 --network=scrypted_default.
 --mount type=bind,source=/etc/codeproject/ai,target=/etc/codeproject/ai.
 \ --mount type=bind,source=/volume5/Exten/CodeProject/md0,target=/app/modules \
   codeproject/ai-server:cuda12_2-2.6.5 

gpu version: NVIDIA-SMI 535.154.05 Driver version: 535.154.05 CUDA version: 12.2  

Face Processing 1.10.2 and Object Detection (YOLOv5 6.2) 1.9.1 modules work using the GPU. 

<img width="1540" alt="image" src="https://github.com/user-attachments/assets/f84f8d54-b7e7-4737-954e-2b1e1c5c51d3">

after installing YOLOv8 module - GPU driver version is downgraded to 11.5 and all modules cannot work with gpu 

Probably in YOLOv8 module installer - error 

**Expected behavior**

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.6.5
 - OS: [e.g. Ubuntu 20.04]
 - System RAM [e.g. 128Gb]
 - GPU (if available) NVIDIA GeForce GTX 1650 (4 GiB) (NVIDIA)
 - GPU RAM (if available)  4Gb

**Additional context**

**Comment by tbc725** [comment]
Try 11.8 version. It works for my Tesla P4. I was able to have Face Processing, YOLOv8 and ALPR all run on GPU.
