### ISSUE TITLE
On clean install, getting import error for YOLOv5 6.2

### ISSUE THREAD

**Issue by mitchconnermeow** [codeproject/CodeProject.AI-Server#123]
08:34:40:Started Object Detection (YOLOv5 6.2) module
08:34:40:detect_adapter.py: Traceback (most recent call last):
08:34:40:detect_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ObjectDetectionYOLOv5-6.2\detect_adapter.py", line 19, in 
08:34:40:detect_adapter.py:     from codeproject_ai_sdk import JSON, ModuleRunner, LogMethod, LogVerbosity, RequestData
08:34:40:detect_adapter.py: ModuleNotFoundError: No module named 'codeproject_ai_sdk'
08:34:40:detect_adapter.py: has exited
08:34:40:Module ObjectDetectionYOLOv5-6.2 has shutdown

For some reason on a fresh install it's wanting to install a version of YOLOv5-6.2 that doesn't appear to be updated for the latest 2.6.5 because it doesn't match the current file on github. When I try to replace the module with the current one from github, the program thinks the file is out of date and wants to update, at which point I get the file requiring codeproject_ai_sdk but it's not present. Not sure how to fix this except to revert back to a previous version for now.

**Comment by mitchconnermeow** [comment]
Update, I just tried installing Codeproject 2.6.2, which was the previous version I was on, and I'm still getting the missing module name 'codeproject_ai_sdk'. For context, I've deleted the entire code project folder from program files and reinstalled from scratch with the same issues. Unless there's codeproject files elsewhere that I'm not aware of, I can't figure out why this module is missing or where to get it.

**Comment by Mohammad699** [comment]
Same issue here
```
21:46:30:Started Training for YoloV5 6.2 module
21:46:30:training_objectdetection_YOLOv5_adapter.py: Traceback (most recent call last):
21:46:30:training_objectdetection_YOLOv5_adapter.py:   File "/app/modules/TrainingObjectDetectionYOLOv5/training_objectdetection_YOLOv5_adapter.py", line 8, in 
21:46:30:training_objectdetection_YOLOv5_adapter.py:     from codeproject_ai_sdk import RequestData, ModuleRunner, ModuleOptions, JSON
21:46:30:training_objectdetection_YOLOv5_adapter.py: ModuleNotFoundError: No module named 'codeproject_ai_sdk'
21:46:30:Module TrainingObjectDetectionYOLOv5 has shutdown
21:46:30:training_objectdetection_YOLOv5_adapter.py: has exited

```

**Comment by ChrisMaunder** [comment]
Please update CodeProject.AI server to the latest.
