### ISSUE TITLE
Video tab isn't showing

### ISSUE THREAD

**Issue by Mohammad699** [codeproject/CodeProject.AI-Server#124]
**Area of Concern**
- [ x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Video tab isn't there

**Screenshots**
![image](https://github.com/user-attachments/assets/fe840c34-0ff8-4c61-8d65-e83696cde743)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.6.5
 - OS: Tuxedo
 - System RAM [12Gb]

**Additional context**

**Comment by ChrisMaunder** [comment]
Open the dev tools for the browser and in the console look for the lines "Webcam detected" or "Webcam detection failed".
