### ISSUE TITLE
asking for advice 

### ISSUE THREAD

**Issue by 19Diablo19** [codeproject/CodeProject.AI-Server#134]
Hi their 
would just like too say this is not an issue this is a me thing 
would like too say thank you too you and your team for all the work you have put into this program it has been a great help with blue iris for a better security system really amazing work 

so my question is how too update too 2.9 if it is ready as i see the update but when i click download latest version i get the 2.6.5 version

as i don't wanna break the program on my side so just wanna confirm i am doing the right thing 
 i have downloaded the source code so (server main) 
 
 oh and almost forgot i am doing this on windows installer 
 
also a heads up i am new to github

**Comment by Tinman77** [comment]
I also would like this info. No where do I see a windows installer here?

**Comment by ChrisMaunder** [comment]
The code is at 2.9 but we haven't made a release yet. It'll be out soon.
