### ISSUE TITLE
Future Maintainers

### ISSUE THREAD

**Issue by ispysoftware** [codeproject/CodeProject.AI-Server#135]
I noticed that a lot of the top people (all?) at codeproject seem to have left - any word on if this project will continue to be worked on or what the plans are for it?

**Comment by MikeLud** [comment]
Go to the Discussion tab, there is details on the change
https://github.com/codeproject/CodeProject.AI-Server/discussions
![image](https://github.com/user-attachments/assets/d642c2ac-d0e0-4a42-aaa6-36f72860c76d)
