### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by ItsSusanBoyle** [codeproject/CodeProject.AI-Server#138]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Dashboard is stating that it cannot update ("Unable to check for updates") via-dashboard nor can it download any modules (Install Modules page is essentially blank). I'm new to this and couldn't find any documentation on troubleshooting this error.

**Expected behavior**
Show that it is able to check for updates. Provide list of available modules to download/install on Install Modules page of dashboard.

**Screenshots**
![image](https://github.com/user-attachments/assets/e1343750-68b9-41e1-b161-d16348621396)
![image](https://github.com/user-attachments/assets/70f432ae-2c50-48b7-b15d-33609e2c91dd)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.8.0
 - OS: Windows Server 2019 Standard build 17763.5936
 - System RAM 16 GB
 - GPU (if available) NA
 - GPU RAM (if available) NA

**Additional context**

**Comment by idontcare99999** [comment]
Same here. Even performed fresh docker install on debian.

**Comment by StefanA-LU** [comment]
It seems that the codeproject side is down.

**Comment by rthfhgyhy567** [comment]
Code project just went out of business

**Comment by MikeLud** [comment]
But CodeProject.AI still lives on, the new link for downloads is below

https://codeproject.github.io/

**Comment by tbc725** [comment]
The "Install Modules" page is back. I was able to download and install the modules.
