### ISSUE TITLE
Download Windows (x64) installer 2.9.2 - unable to install due to an Internal error

### ISSUE THREAD

**Issue by sym0nd0** [codeproject/CodeProject.AI-Server#165]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
When trying to install 2.9.2 on Windows, upon clicking the install button it posts:

Setup
Internal error: DownloadTemporaryFile: Invalid Url value.

Clicking the OK button closes the error popup but cannot proceed with the install as clicking Install again loops the same error.

**Expected behavior**
To be able to install 2.9.2 on Windows.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b692c57-3ca6-48c0-b93a-a49bd3abe383)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.8
 - OS: Windows 10 Pro 22H2
 - System RAM 16GB
 - GPU (if available) Nvidia GeForce GT 1030
 - GPU RAM (if available)  2GB

**Comment by tinker3433** [comment]
I am having the same issue, same error message.

**Comment by mag1024** [comment]
Manually installing .NET 9.0 runtime before running the project installer seems to work around the installer error -- however, module installation seems to also be having some issues, so you may want to wait for the next version anyway.

**Comment by ChrisMaunder** [comment]
Thanks for the report. I'll go grab a large hammer.

**Comment by tinker3433** [comment]
> Manually installing .NET 9.0 runtime before running the project installer seems to work around the installer error -- however, module installation seems to also be having some issues, so you may want to wait for the next version anyway.

Thanks, This worked to get it past the initial error and the install compleated

**Comment by ChrisMaunder** [comment]
I've uploaded a small tweak to the 2.9.2 installer (No build number update) that _may_ solve the issue. I have a plan B if that doesn't work

**Comment by MikeLud** [comment]
> I've uploaded a small tweak to the 2.9.2 installer (No build number update) that _may_ solve the issue. I have a plan B if that doesn't work

I think you need a bigger hammer, maybe a sledge hammer. I manually installed .NET 9.0 and the install worked but when the Dashboard opens up it crashes and no modules get installed.

![image](https://github.com/user-attachments/assets/9129021f-2001-4476-8db9-2bb2f4e67657)

**Comment by ChrisMaunder** [comment]
That's almost big enough. Can you elaborate on "when the Dashboard opens up it crashes and no modules get installed". The browser crashes , the dashboard throws an error or the server stops working? Any system logs?

I've just pushed a 2.9.3. As usual, everything's been working perfectly for me all day. I did have an issue with the .NET YOLOv5 module where it was using the wrong folder, and I also fixed an issue with the module listing not being accurate (issue from moving from dynamic system on CodeProject to static file on bunny.net)

**Comment by mag1024** [comment]
Alas, I don't think the installer issue is fixed with 2.9.3 -- I removed the AI server, and the .NET 9.0, and I get `Internal error: DownloadTemporaryFile: Invalid Url value.`

After manually pre-installing the runtime, I get a successful installation, but I still have the issue where some of the YOLO Object Detection modules (.NET, 3.1, 6.2, training for YoloV5 6.2) are listed twice, once as `Available`, and once as `Not Available`.

The one thing that is fixed is YOLOv5 .NET -- it now installs fine.

**Comment by MikeLud** [comment]
> That's almost big enough. Can you elaborate on "when the Dashboard opens up it crashes and no modules get installed". The browser crashes , the dashboard throws an error or the server stops working? Any system logs?
> 
The server crashes, no errors or log folder does not get created. Tried running the server in a command prompt and does not run.

**Comment by ChrisMaunder** [comment]
Found and fixed this issue

**Comment by MikeLud** [comment]
> @MikeLud If you launch the server in a command terminal does anything show up? Does task manager show there is still an instance of CodeProject.AI server running?

I have v2.9.3 working now, the issue was I had to install all three runtimes
![image](https://github.com/user-attachments/assets/a9190626-b52a-4747-9477-0de9d1b30b64)
