### ISSUE TITLE
not for Linux :-(

### ISSUE THREAD

**Issue by alexbn71** [codeproject/CodeProject.AI-Server#17]
It seams there are many issues on Linux... the most important is that I suspect a big problem of memory leak, not so rare situation for .NET porting on Linux :(

I hope you will have time to spent to to make it work well on Linux as well.

the only criticism that I allow myself to make ... is that when you declare a multi-platform project you should decide to make it work equally on all of them. I say this because it is not the first .NET project that I see that passes itself off as compatible with Linux when only Linux problems remain unsolved.

I know that you project it's new ... but I put my hands on ;-)

**Comment by ChrisMaunder** [comment]
Thanks for the warning about the memory leak. 

Which version of Linux are you using, and which version of CodeProject.AI Server are you using?

**Comment by alexbn71** [comment]
kernel 5.19.7,  Docker image of CodeProject.AI Server is 1.6.2

Maybe it's a normal condition for how your project is set up. I noticed that when the server starts it uses .7GB of RAM on idle state. Submitting some image processing the RAM consumptiom rise up to 3/4GB then stay around this value forever.
