### ISSUE TITLE
Mac m1 installation info

### ISSUE THREAD

**Issue by diablozzq** [codeproject/CodeProject.AI-Server#18]
Hello - I can’t seem to find any information on the proper dependencies and installation for Mac M1 with GPU support.  

Docker didn’t have an arm image, and I tried setting up the dev environment, but couldn’t get it working.  If I had a guide specific to Mac and what dependencies to install, I think I could get it working.

all I need is short, to the point steps.  I’m pretty confident I’m close.  

Thanks for all your work on this.  

I installed python 3.9 and 3.8 via Brew.  And installed the Mac Arm dot net 6.0 SDK.  Built the dev environment and opened VSCode, but was unable to get the server to launch.  Rather than debug my end, just knowing if I should use Dot net x64 or arm or docker x64 or whatever
 would help a ton.

**Comment by ChrisMaunder** [comment]
All of this is taken care of for you.

After cloning the repo, just go to /Installers/Dev and type `bash setup.sh`. This will setup the python interpreters, create the virtual environments, install the python packages, and download the models. All you have to do is compile and run.

**Comment by arudnitsky** [comment]
Is it possible to get a docker image made for Mac silicon? I strongly prefer not installing via script that installs things in all kinds of places. I have specific requirements for versions of things currently because of what I'm working on. I don't want to mess that up.

**Comment by arudnitsky** [comment]
Thanks, @ChrisMaunder! I appreciate the quick response.

**Comment by arudnitsky** [comment]
@ChrisMaunder Have you had a chance to get this set up?

**Comment by ChrisMaunder** [comment]
Here you go: docker pull codeproject/ai-server:arm64-1.6.8.0

**Comment by arudnitsky** [comment]
Very much appreciated, @ChrisMaunder
