### ISSUE TITLE
Download Windows (x64) installer 2.9.3 - unable to install due to an Internal error (same as #165)

### ISSUE THREAD

**Issue by sym0nd0** [codeproject/CodeProject.AI-Server#185]
Area of Concern

 Server
 Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
 Installer
 Runtime [e.g. Python3.7, .NET]
 Module packages [e.g. PyTorch)
 Something else
Describe the bug
When trying to install 2.9.3 on Windows, upon clicking the install button it posts:

Setup
Internal error: DownloadTemporaryFile: Invalid Url value.

Clicking the OK button closes the error popup but cannot proceed with the install as clicking Install again loops the same error.

Same error as #165.

Expected behaviour
To be able to install 2.9.3 on Windows 10 Pro.

Screenshots
![image](https://github.com/user-attachments/assets/69e3e77c-b1ae-49f3-ae78-f89f67411cb2)

Your System (please complete the following information):

CodeProject.AI Server version: 2.8
OS: Windows 10 Pro 22H2
System RAM 16GB
GPU (if available) Nvidia GeForce GT 1030
GPU RAM (if available) 2GB

**Comment by ChrisMaunder** [comment]
Please re-download the installer. The installer has been bumped to a 2.9.3.1 (though the server is still 2.9.3)
