### ISSUE TITLE
Custom-modules in Docker

### ISSUE THREAD

**Issue by DeFlanko** [codeproject/CodeProject.AI-Server#190]
**Area of Concern**
- [ ] Server
- [x] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [x] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
```log
14:31:32:Object Detection (YOLOv5 6.2): /app/preinstalled-modules/ObjectDetectionYOLOv5-6.2/custom-models/delivery.pt does not exist
14:31:32:Object Detection (YOLOv5 6.2): Unable to create YOLO detector for model delivery
14:31:33:Object Detection (YOLOv5 6.2): /app/preinstalled-modules/ObjectDetectionYOLOv5-6.2/custom-models/package.pt does not exist
14:31:33:Object Detection (YOLOv5 6.2): Unable to create YOLO detector for model package
```
**Expected behavior**
see the pt files

**Screenshots**
![image](https://github.com/user-attachments/assets/a1daf2dd-b1e8-4636-a87f-49a088f1a97e)
![image](https://github.com/user-attachments/assets/9e1358d2-2c67-4e8a-9965-f22065b47fb1)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.8
 - OS: Docker Desktop 4.36.0
 - System RAM [64Gb]
 - GPU (if available) [NVIDIA GeForce RTX 3070]
 - GPU RAM (if available)  [e.g. 8Gb]
 - image: codeproject/ai-server:cuda12_2-2.8.0

**Additional context**
i thought having the pt files in the folder to match would resolve it but still looks like they cannot be found.

**Comment by ChrisMaunder** [comment]
https://codeproject.github.io/codeproject.ai/install/running_in_docker.html#common-example-specifying-a-folder-for-custom-object-detection-files-for-the-objectdetectionyolo-module

**Comment by DeFlanko** [comment]
Thank you @ChrisMaunder, Absolutely fixed the issue!
