### ISSUE TITLE
virus found on winx64 installer (preview)

### ISSUE THREAD

**Issue by ispysoftware** [codeproject/CodeProject.AI-Server#195]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [x] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Downloading the win x64 installer for preview version triggers a virus warning

**Screenshots**
![image](https://github.com/user-attachments/assets/005c34ab-f680-4c71-8d5b-1ae1281943f7)

**Comment by MidnightLink** [comment]
Interesting enough, the zip file is getting flagged but not the actual program itself. It looks to be a false positive 

Zip file: https://www.virustotal.com/gui/file/d06d5e01d7de6928109ae275809371e6e5f8922ea44f39dbd578e0e2543df80d/details

Installer once unzipped: https://www.virustotal.com/gui/file/e59cc74f5e4e40f1162e0f5e25e2ec20e00eb99dff31fae8a792f0cdf0354aca/details

**Comment by ChrisMaunder** [comment]
The best option is to see if your anti-virus software has the means to send in a report, and then send in the installer for them to test.
