### ISSUE TITLE
Feature Request Set Service API Url via env variable

### ISSUE THREAD

**Issue by scho0ck** [codeproject/CodeProject.AI-Server#2]
Running SenseAI on a remote Server could we implement a variable to set "Service API Url"

Thanks

**Comment by kars85** [comment]
If I understand correctly, by default the API field defaults to http://localhost:5000 which is inconvenient to have to set each time the page is loaded/refreshed. An environment variable to set the html to load a defined IP/hostname would be convenient.

![image](https://user-images.githubusercontent.com/6616548/176742071-80a4c9dd-ca49-4f4c-84ae-f559ebc0b82d.png)

**Comment by ChrisMaunder** [comment]
That page is launched by the AI server itself, so "localhost" is the correct location *for that window*. 

I'm assuming what you are looking to do is launch the dashboard from a different machine and have the URL populated automatically. An environment variable on the server won't help a webpage on a different server (different machines) but there's also the issue with a webpage not having access to a system's environment variables.

What we could do is sniff the URL of the dashboard page and use that as the URL for the server (the IPs must be the same given the server is serving the dashboard page)

**Comment by scho0ck** [comment]
With the latest release this seem to be solved

**Comment by ChrisMaunder** [comment]
Yes, for v1.5.1 this feature has been added.
