### ISSUE TITLE
apiServiceUrl  issue

### ISSUE THREAD

**Issue by Major2000** [codeproject/CodeProject.AI-Server#20]
**Area of Concern**
- [x] Server

**Description**
when I deployed the AI server to okteto cloud platform, the end-point is `https://....`. this causes server not to be fount by the client
when I review the code I found this javascript in Visio.html
```javascript
    <script type="text/javascript">

		const useSVG            = true;
		const pingFrequency     = 1000; // milliseconds
                const apiServiceUrl     = "http://" + (window.location.hostname || "localhost")
                                + ":" + (window.location.port || 32168);
		const serviceTimeoutSec = 20;
		let serverOnline        = false;
               ...
      </script>
```
The variable `apiServiceUrl` has got the format `http://` and appends the link there. I hope it refers to Localhost links only
What about other scenarios like when the server is deployed to remote cloud??

**Expected behavior**
The `apiServerUrl` shouldn't be only local host Url other means should also be possible

**Screenshots**
![Screenshot 2022-10-01 174206](https://user-images.githubusercontent.com/65360332/193414911-1c88a03c-6ea6-45fc-a6e1-a2b73b5804c1.png)

**System**
 - CodeProject.AI Server version: 1.6.0.0
 - OS: Windows 10 21H2
 - System RAM: 8GB
 - GPU: AMD Radeon HD 8750M
 - GPU RAM: 4Gb

**Comment by ChrisMaunder** [comment]
The initial URL that's set has been corrected to include protocol
```javascript
const apiServiceUrl = (window.location.protocol || "http:") + "//"
                    + (window.location.hostname || "localhost")
                    + ":" + (window.location.port || 32168);
```
However, regardless of the initial setting, you can update it to whatever URL you have your CodeProject.AI Server installed on just by editing the value in that URL text box

**Comment by Major2000** [comment]
Thanks
