### ISSUE TITLE
Update to 2.9.4 error

### ISSUE THREAD

**Issue by ac2323** [codeproject/CodeProject.AI-Server#207]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

After updating the Cuda 12 Docker container to the latest version 2.9.4, YOLOv8 stops working. The server returns this error: 

`detect_adapter.py: ModuleNotFoundError: No module named 'ultralytics'.`

Updating yolov8 does not help nor does uninstalling/reinstalling. Running the 2.8 container with the updated modules does not help.

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.9.4
 - OS: Ubuntu 22.04.5
 - System RAM: 12.7GB
 - GPU (if available):  GeForce RTX 3060
 - GPU RAM (if available): 12GB

**Additional context**

2.8 (pre-update) works just fine

**Comment by ChrisMaunder** [comment]
Do you have the install log handy? After you install, if you click the info button on the module's row in the dashboard the install log should be shown. Failing that, uninstall and reinstall **setting verbosity to loud**  and paste the install logs here

**Comment by ac2323** [comment]
Here's the install log:

`12:26:21:System:           Docker (aa8ce07c5d4d)
12:26:21:Operating System: Linux (Ubuntu 22.04 Jammy Jellyfish)
12:26:21:CPUs:             QEMU Virtual CPU version 2.5+
12:26:21:                  1 CPU x 8 cores. 8 logical processors (x64)
12:26:21:GPU (Primary):    NVIDIA GeForce RTX 3060 (12 GiB) (NVIDIA)
12:26:21:                  Driver: 550.135, CUDA: 12.4 (up to: 12.4), Compute: 8.6, cuDNN: 8.9.6
12:26:21:System RAM:       12 GiB
12:26:21:Platform:         Linux
12:26:21:BuildConfig:      Release
12:26:21:Execution Env:    Docker
12:26:21:Runtime Env:      Production
12:26:21:Runtimes installed:
12:26:21:  .NET runtime:     9.0.0
12:26:21:  .NET SDK:         Not found
12:26:21:  Default Python:   3.10.12
12:26:21:  Go:               Not found
12:26:21:  NodeJS:           Not found
12:26:21:  Rust:             Not found
12:26:21:App DataDir:      /etc/codeproject/ai
12:26:21:Video adapter info:
12:26:21:STARTING CODEPROJECT.AI SERVER
12:26:21:RUNTIMES_PATH             = /app/runtimes
12:26:21:PREINSTALLED_MODULES_PATH = /app/preinstalled-modules
12:26:21:DEMO_MODULES_PATH         = /app/src/demos/modules
12:26:21:EXTERNAL_MODULES_PATH     = /CodeProject.AI-Modules
12:26:21:MODULES_PATH              = /app/modules
12:26:21:PYTHON_PATH               = /bin/ubuntu/%PYTHON_NAME%/venv/bin/python3
12:26:21:Data Dir                  = /etc/codeproject/ai
12:26:21:Server version:   2.9.4
12:26:21:ModuleRunner Start
12:26:21:Rerunning modules setup because the Docker container ID has changed.
12:26:21:Installing module 'All Modules'
12:26:21:Installer script at '/app/setup.sh'
12:26:21:Setting verbosity to quiet
12:26:21:Hi Docker! We will disable shared python installs for downloaded modules
12:26:21:Overriding address(es) 'http://+:32168, http://+:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
12:26:21:(No schemas means: we can't detect if you're in light or dark mode)
12:26:21:          Setting up CodeProject.AI Development Environment           
12:26:21:======================================================================
12:26:21:                   CodeProject.AI Installer                           
12:26:21:======================================================================
12:26:21:18.08 GiB of 75.09 GiB available on Docker (linux ubuntu x86_64 - linux)
12:26:21:Installing xz-utils...
12:26:25:Reading package lists...
12:26:25:Building dependency tree...
12:26:25:Reading state information...
12:26:25:0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
12:26:25:General CodeProject.AI setup                                          
12:26:25:Setting permissions on runtimes folder...done
12:26:25:Setting permissions on general downloads folder...done
12:26:25:Creating module asset downloads folder...done
12:26:25:Setting permissions on module asset downloads folder...done
12:26:25:Setting permissions on modules folder...done
12:26:25:Creating models folder...done
12:26:25:Setting permissions on models folder...done
12:26:25:Setting permissions on persisted data folder...done
12:26:25:GPU support                                                           
12:26:25:Installing NVIDIA keyring
12:26:26:Server: This is a new, unreleased version
12:26:26:Current Version is 2.9.4
12:26:26:  Installing CUDA toolkit
12:26:28: Installing cuda kit
12:30:43: CUDA (NVIDIA) Present: Yes (CUDA 12.4, cuDNN 8.9.6)
12:30:47:ROCm (AMD) Present:    (attempt to install rocminfo... ) No
12:30:47:MPS (Apple) Present:   No
12:30:47:Processing Included CodeProject.AI Server Modules                     
12:30:48:Reading module settings.......done
12:30:48:Processing module FaceProcessing 1.12.0 (Internal)                    
12:30:48:Downloaded modules must have local Python install. Changing install location
12:30:48:Installing Python 3.8
12:30:48:Python 3.8 is already installed
12:30:55:Ensuring PIP in base python install...  done
12:30:56:Upgrading PIP in base python install... done
12:30:56:Installing Virtual Environment tools for Linux...
12:31:01:Searching for python3-pip python3-setuptools python3.8...All good.
12:31:04:Creating Virtual Environment (Local)... done
12:31:04:Checking for Python 3.8...(Found Python 3.8.20) All good
12:31:07:Upgrading PIP in virtual environment... done
12:31:10:Installing updated setuptools in venv... done
12:31:19:Downloading Face models...Expanding... done.
12:31:19:Moving contents of models-face-pt.zip to assets...done.
12:31:19:Installing Python packages for Face Processing
12:31:19:Installing GPU-enabled libraries: If available
12:31:21:Searching for python3-pip...All good.
12:31:22:Ensuring PIP compatibility... done
12:31:22:Python packages will be specified by requirements.linux.cuda12.txt
12:31:33:  - Installing Pandas, a data analysis / data manipulation tool... (✅ checked) done
12:31:50:  - Installing CoreMLTools, for working with .mlmodel format models... (✅ checked) done
12:31:59:  - Installing OpenCV, the Open source Computer Vision library... (✅ checked) done
12:32:02:  - Installing Pillow, a Python Image Library... (✅ checked) done
12:32:10:  - Installing SciPy, a library for mathematics, science, and engineering... (✅ checked) done
12:32:11:  - Installing PyYAML, a library for reading configuration files...Already installed
12:33:49:  - Installing PyTorch, an open source machine learning framework... (✅ checked) done
12:34:43:  - Installing TorchVision, for working with computer vision models... (✅ checked) done
12:34:58:  - Installing Seaborn, a data visualization library based on matplotlib... (✅ checked) done
12:35:10:  - Installing the CodeProject.AI SDK... (✅ checked) done
12:35:10:Scanning modulesettings for downloadable models...No models specified
12:35:19:Fusing layers... 
12:35:20:YOLOv5m summary: 316 layers, 21468630 parameters, 0 gradients
12:35:22:Self test: Self-test passed
12:35:22:Module setup time 00:04:35
12:35:22:Reading module settings.......done
12:35:22:Processing module ObjectDetectionYOLOv8 1.6.0 (Internal)              
12:35:22:Installing Python 3.8
12:35:22:Python 3.8 is already installed
12:35:29:Ensuring PIP in base python install...  done
12:35:30:Upgrading PIP in base python install... done
12:35:30:Installing Virtual Environment tools for Linux...
12:35:35:Searching for python3-pip python3-setuptools python3.8...All good.
12:35:38:Creating Virtual Environment (Local)... done
12:35:38:Checking for Python 3.8...(Found Python 3.8.20) All good
12:35:41:Upgrading PIP in virtual environment... done
12:35:43:Installing updated setuptools in venv... done
12:35:43:Installing Python packages for Object Detection (YOLOv8)
12:35:43:Installing GPU-enabled libraries: If available
12:35:44:Searching for python3-pip...All good.
12:35:46:Ensuring PIP compatibility... done
12:35:46:Python packages will be specified by requirements.linux.cuda12.txt
12:35:50:  - Installing NumPy, a package for scientific computing... (✅ checked) done
12:36:45:  - Installing PyTorch, an open source machine learning framework... (✅ checked) done
12:37:53:  - Installing TorchVision, for working with computer vision models... (✅ checked) done
12:39:15:  - Installing Ultralytics package for object detection in images... (❌ failed check) done
12:39:21:  - Installing the CodeProject.AI SDK... (✅ checked) done
12:39:21:Scanning modulesettings for downloadable models...Processing model list
12:39:30:Downloading YOLOv8 Object Detection all sizes...Expanding... done.
12:39:30:Moving contents of objectdetection-coco-yolov8-pt-nsmlx.zip to assets...done.
12:39:38:Downloading YOLOv8 Object Segmentation all sizes...Expanding... done.
12:39:38:Moving contents of objectsegmentation-coco-yolov8-pt-nsmlx.zip to assets...done.
12:39:40:Downloading YOLOv8 Object Custom models...Expanding... done.
12:39:40:Moving contents of objectdetection-custom-yolov8-pt-m.zip to custom-models...done.
12:39:45:Traceback (most recent call last):
12:39:45:  File "detect_adapter.py", line 16, in 
12:39:45:    from detect import do_detection
12:39:45:  File "/app/modules/ObjectDetectionYOLOv8/detect.py", line 11, in 
12:39:45:    from ultralytics import YOLO
12:39:45:ModuleNotFoundError: No module named 'ultralytics'
12:39:46:Self test: Self-test failed
12:39:46:Module setup time 00:04:24
12:39:46:Processing External CodeProject.AI Server Modules                     
12:39:46:No external modules found
12:39:46:Module setup Complete
12:39:46:                Setup complete                                        
12:39:46:Total setup time 00:13:25
12:39:46:SETUP FAILED:
12:39:46: - [Int: ObjectDetectionYOLOv8 @ /app/modules/ObjectDetectionYOLOv8] Self-test failed
12:39:46:Installer exited with code 1
12:39:46:Starting Background AI Modules
12:39:49:Running module using: /app/modules/FaceProcessing/bin/ubuntu/python38/venv/bin/python3
12:39:49:
12:39:49:Starting /app...essing/bin/ubuntu/python38/venv/bin/python3 "/app.../FaceProcessing/intelligencelayer/face.py"
12:39:49:
12:39:49:Attempting to start FaceProcessing with /app/modules/FaceProcessing/bin/ubuntu/python38/venv/bin/python3 "/app/modules/FaceProcessing/intelligencelayer/face.py"
12:39:49:Module 'Face Processing' 1.12.0 (ID: FaceProcessing)
12:39:49:Valid:            True
12:39:49:Module Path:      <root>/modules/FaceProcessing
12:39:49:Module Location:  Internal
12:39:49:AutoStart:        True
12:39:49:Queue:            faceprocessing_queue
12:39:49:Runtime:          python3.8
12:39:49:Runtime Location: Shared
12:39:49:FilePath:         intelligencelayer/face.py
12:39:49:Start pause:      3 sec
12:39:49:Parallelism:      0
12:39:49:LogVerbosity:
12:39:49:Platforms:        all,!jetson
12:39:49:GPU Libraries:    installed if available
12:39:49:GPU:              use if supported
12:39:49:Accelerator:
12:39:49:Half Precision:   enable
12:39:49:Environment Variables
12:39:49:APPDIR             = <root>/modules/FaceProcessing/intelligencelayer
12:39:49:DATA_DIR           = /etc/codeproject/ai
12:39:49:MODE               = MEDIUM
12:39:49:MODELS_DIR         = <root>/modules/FaceProcessing/assets
12:39:49:PROFILE            = desktop_gpu
12:39:49:USE_CUDA           = True
12:39:49:YOLOv5_AUTOINSTALL = false
12:39:49:YOLOv5_VERBOSE     = false
12:39:49:
12:39:49:Started Face Processing module
12:39:52:Running module using: /app/modules/ObjectDetectionYOLOv8/bin/ubuntu/python38/venv/bin/python3
12:39:52:
12:39:52:
12:39:52:Module 'Object Detection (YOLOv8)' 1.6.0 (ID: ObjectDetectionYOLOv8)
12:39:52:Valid:            True
12:39:52:Module Path:      <root>/modules/ObjectDetectionYOLOv8
12:39:52:Module Location:  Internal
12:39:52:AutoStart:        True
12:39:52:Starting /app...YOLOv8/bin/ubuntu/python38/venv/bin/python3 "/app...s/ObjectDetectionYOLOv8/detect_adapter.py"
12:39:52:Attempting to start ObjectDetectionYOLOv8 with /app/modules/ObjectDetectionYOLOv8/bin/ubuntu/python38/venv/bin/python3 "/app/modules/ObjectDetectionYOLOv8/detect_adapter.py"
12:39:52:Queue:            objectdetection_queue
12:39:52:Runtime:          python3.8
12:39:52:Runtime Location: Local
12:39:52:FilePath:         detect_adapter.py
12:39:52:Start pause:      1 sec
12:39:52:Parallelism:      0
12:39:52:LogVerbosity:
12:39:52:Platforms:        all
12:39:52:GPU Libraries:    installed if available
12:39:52:GPU:              use if supported
12:39:52:Accelerator:
12:39:52:Half Precision:   enable
12:39:52:Environment Variables
12:39:52:APPDIR            = <root>/modules/ObjectDetectionYOLOv8
12:39:52:CUSTOM_MODELS_DIR = <root>/modules/ObjectDetectionYOLOv8/custom-models
12:39:52:MODELS_DIR        = <root>/modules/ObjectDetectionYOLOv8/assets
12:39:52:MODEL_SIZE        = Medium
12:39:52:USE_CUDA          = True
12:39:52:YOLO_VERBOSE      = false
12:39:52:
12:39:52:Started Object Detection (YOLOv8) module
12:39:53:detect_adapter.py: Traceback (most recent call last):
12:39:53:detect_adapter.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
12:39:53:detect_adapter.py:   File "/app/modules/ObjectDetectionYOLOv8/detect_adapter.py", line 16, in 
12:39:53:detect_adapter.py:     from detect import do_detection
12:39:53:detect_adapter.py:   File "/app/modules/ObjectDetectionYOLOv8/detect.py", line 11, in 
12:39:53:detect_adapter.py:     from ultralytics import YOLO
12:39:53:detect_adapter.py: ModuleNotFoundError: No module named 'ultralytics'
12:39:53:Module ObjectDetectionYOLOv8 has shutdown
12:39:55:face.py: Vision AI services setup: Retrieving environment variables...
12:39:55:face.py: GPU in use: NVIDIA GeForce RTX 3060
12:39:55:face.py: APPDIR:       /app/modules/FaceProcessing/intelligencelayer
12:39:55:face.py: PROFILE:      desktop_gpu
12:39:55:face.py: USE_CUDA:     True
12:39:55:face.py: DATA_DIR:     /etc/codeproject/ai
12:39:55:face.py: MODELS_DIR:   /app/modules/FaceProcessing/assets
12:39:55:face.py: Running init for Face Processing
12:39:55:face.py: MODE:         MEDIUM
`

**Comment by ChrisMaunder** [comment]
Try reinstalling the ObjectDetection (.NET) module. I've made an update that fixes the issues with the ultralytics package install

**Comment by ac2323** [comment]
I'm on Linux Docker with CUDA. Is the .NET ObjectDetection module needed?
Also, is the new version going to be on Docker Hub?

Thanks for your help!

**Comment by ChrisMaunder** [comment]
Sorry - mixing up modules. Try reinstalling the Object Detection YOLOv5 6.2 module.

The .NET Module will do the same as the Python 6.2 module, it's just written using a different stack
