### ISSUE TITLE
is my cat a dog?

### ISSUE THREAD

**Issue by alexbn71** [codeproject/CodeProject.AI-Server#21]
It was never recognized as a cat. Dozens of day and night photos passed by the camera have always identified it as a dog.

![c30705bd-28c6-4b2f-a3b3-1d00b18fdbcd](https://user-images.githubusercontent.com/20998190/193739651-adc06a74-68bc-4509-ad74-90dcfb44972b.jpg)

**Comment by MikeLud** [comment]
Which model are you using? You can try the ipcam-animal model it might identify the cat as a cat.

**Comment by alexbn71** [comment]
Yes it works but not very useful since is seems that in this way only animals are detected in the scene, am I right?

![image](https://user-images.githubusercontent.com/20998190/193745013-794a2f45-06a9-4a21-a301-518825f21548.png)

**Comment by MikeLud** [comment]
You can try the ipcam-combined model this might work for your use case

IPcam-combined Labels: - person, bicycle, car, motorcycle, bus, truck, bird, cat, dog, horse, sheep, cow, bear, deer, rabbit, raccoon, fox, skunk, squirrel, pig

**Comment by ChrisMaunder** [comment]
Detection of objects (and the issues surrounding this) are a separate issue that we're going to be addressing in a future extension of our work. I'm closing (with all respect) this since this isn't a code / system issue, but rather a data / training issue
