### ISSUE TITLE
Download Page does not show latest version

### ISSUE THREAD

**Issue by finnaGIT** [codeproject/CodeProject.AI-Server#210]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [X] Something else

**Describe the bug**
The [download](https://codeproject.github.io/codeproject.ai/latest.html)  page currently shows & downloads 2.9.4 but 2.9.5 is current.

**Expected behavior**
2.9.5 is linked on the download page.

**Screenshots**
none

**Your System (please complete the following information):**
n/a

**Additional context**
none

**Comment by ChrisMaunder** [comment]
Corrected

**Comment by finnaGIT** [comment]
In case any one was wondering, 2.9.4 was in fact current - it was github which incorrectly stated 2.9.5 was current.

Thanks for your work on this project @ChrisMaunder !!

**Comment by ChrisMaunder** [comment]
It was totally on me. I made a typo and set a 2.9.5 release instead of the current 2.9.4.
