### ISSUE TITLE
errors in face module after updating from 2.8.0 to 2.9.4 in ubuntu 22.04 i've got "Unable to load the face detector"

### ISSUE THREAD

**Issue by divemasterjm** [codeproject/CodeProject.AI-Server#211]
08:01:36:Preparing to install module 'FaceProcessing'
08:01:36:Downloading module 'FaceProcessing'
08:01:36:Installing module 'FaceProcessing'
08:01:36:FaceProcessing: Setting verbosity to quiet
08:01:36:FaceProcessing: /usr/bin/codeproject.ai-server-2.9.4/.env file not found
08:01:36:FaceProcessing:              Installing CodeProject.AI Analysis Module                
08:01:36:FaceProcessing: ======================================================================
08:01:36:FaceProcessing:                    CodeProject.AI Installer                           
08:01:36:FaceProcessing: ======================================================================
08:01:36:FaceProcessing: 12.06 GiB of 50.01 GiB available on linux (linux ubuntu x86_64 - linux)
08:01:36:FaceProcessing: Installing xz-utils...
08:01:38:FaceProcessing: General CodeProject.AI setup                                          
08:01:38:FaceProcessing: Setting permissions on runtimes folder...done
08:01:38:FaceProcessing: Setting permissions on general downloads folder...done
08:01:38:FaceProcessing: Setting permissions on module asset downloads folder...done
08:01:38:FaceProcessing: Setting permissions on modules folder...done
08:01:38:FaceProcessing: Setting permissions on models folder...done
08:01:38:FaceProcessing: Setting permissions on persisted data folder...done
08:01:38:FaceProcessing: GPU support                                                           
08:01:38:FaceProcessing: CUDA (NVIDIA) Present: Yes (CUDA 11.5, cuDNN 9.5.1)
08:01:38:FaceProcessing: ROCm (AMD) Present:    No
08:01:38:FaceProcessing: MPS (Apple) Present:   No
08:01:38:FaceProcessing: Reading module settings.......done
08:01:38:FaceProcessing: Processing module FaceProcessing 1.12.1 (Internal)                    
08:01:38:FaceProcessing: Installing Python 3.8
08:01:38:FaceProcessing: Python 3.8 is already installed
08:01:44:FaceProcessing: Ensuring PIP in base python install...  done
08:01:45:FaceProcessing: Upgrading PIP in base python install... done
08:01:45:FaceProcessing: Virtual Environment already present
08:01:45:FaceProcessing: Checking for Python 3.8...(Found Python 3.8.20) All good
08:01:46:FaceProcessing: Upgrading PIP in virtual environment... done
08:01:48:FaceProcessing: Installing updated setuptools in venv... done
08:01:51:FaceProcessing: Downloading Face models... already exists...Expanding... done.
08:01:52:FaceProcessing: Moving contents of models-face-pt.zip to assets...done.
08:01:52:FaceProcessing: Installing Python packages for Face Processing
08:01:52:FaceProcessing: Installing GPU-enabled libraries: If available
08:01:52:FaceProcessing: Searching for python3-pip...All good.
08:01:54:FaceProcessing: Ensuring PIP compatibility... done
08:01:54:FaceProcessing: Python packages will be specified by requirements.linux.cuda11_5.txt
08:01:54:FaceProcessing:   - Installing Pandas, a data analysis / data manipulation tool...Already installed
08:01:55:FaceProcessing:   - Installing CoreMLTools, for working with .mlmodel format models...Already installed
08:01:55:FaceProcessing:   - Installing OpenCV, the Open source Computer Vision library...Already installed
08:01:56:FaceProcessing:   - Installing Pillow, a Python Image Library...Already installed
08:01:56:FaceProcessing:   - Installing SciPy, a library for mathematics, science, and engineering...Already installed
08:01:57:FaceProcessing:   - Installing PyYAML, a library for reading configuration files...Already installed
08:01:57:FaceProcessing:   - Installing PyTorch, an open source machine learning framework...Already installed
08:01:58:FaceProcessing:   - Installing TorchVision, for working with computer vision models...Already installed
08:01:58:FaceProcessing:   - Installing Seaborn, a data visualization library based on matplotlib...Already installed
08:01:59:FaceProcessing:   - Installing the CodeProject.AI SDK...Already installed
08:01:59:FaceProcessing: Scanning modulesettings for downloadable models...No models specified
08:02:08:FaceProcessing: Self test: Self-test failed
08:02:08:FaceProcessing: Module setup time 00:00:30
08:02:08:FaceProcessing: Install failed: Self-test failed
08:02:08:FaceProcessing:                 Setup complete                                        
08:02:08:FaceProcessing: Total setup time 00:00:32
08:02:08:FaceProcessing: SETUP FAILED:
08:02:08:FaceProcessing:  - [Int: FaceProcessing] Self-test failed
08:02:08:Module FaceProcessing installed successfully.
08:02:08:Installer exited with code 1
08:02:08:
08:02:08:Module 'Face Processing' 1.12.1 (ID: FaceProcessing)
08:02:08:Valid:            True
08:02:08:Module Path:      <root>/modules/FaceProcessing
08:02:08:Module Location:  Internal
08:02:08:AutoStart:        True
08:02:08:Queue:            faceprocessing_queue
08:02:08:Runtime:          python3.8
08:02:08:Runtime Location: Shared
08:02:08:FilePath:         intelligencelayer/face.py
08:02:08:Start pause:      3 sec
08:02:08:Parallelism:      0
08:02:08:LogVerbosity:
08:02:08:Platforms:        all,!jetson
08:02:08:GPU Libraries:    installed if available
08:02:08:GPU:              use if supported
08:02:08:Accelerator:
08:02:08:Half Precision:   enable
08:02:08:Environment Variables
08:02:08:APPDIR             = <root>/modules/FaceProcessing/intelligencelayer
08:02:08:DATA_DIR           = /etc/codeproject/ai
08:02:08:MODE               = MEDIUM
08:02:08:MODELS_DIR         = <root>/modules/FaceProcessing/assets
08:02:08:PROFILE            = desktop_gpu
08:02:08:USE_CUDA           = True
08:02:08:YOLOv5_AUTOINSTALL = false
08:02:08:YOLOv5_VERBOSE     = false
08:02:08:
08:02:08:Started Face Processing module
08:02:11:face.py: GPU in use: NVIDIA GeForce RTX 3050
08:02:11:Module FaceProcessing started successfully.
08:02:08:
08:02:08:Started Face Processing module
08:02:11:face.py: GPU in use: NVIDIA GeForce RTX 3050
08:02:11:Module FaceProcessing started successfully.
08:03:30:Response rec'd from Face Processing command 'list' (...0aa050) took 0ms
08:04:02:Face Processing:  [TypeError] : Traceback (most recent call last):
  File "/usr/bin/codeproject.ai-server-2.9.4/modules/FaceProcessing/intelligencelayer/face.py", line 207, in _init_models
    self.faceclassifier = FaceRecognitionModel(model_path,
  File "/usr/bin/codeproject.ai-server-2.9.4/modules/FaceProcessing/intelligencelayer/./recognition/process.py", line 28, in __init__
    load_model(self.model, model_path)
  File "/usr/bin/codeproject.ai-server-2.9.4/modules/FaceProcessing/intelligencelayer/./recognition/process.py", line 11, in load_model
    checkpoint = torch.load(path, map_location=lambda storage, loc: storage, weights_only=True)
  File "/usr/bin/codeproject.ai-server-2.9.4/runtimes/bin/ubuntu/python38/venv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/bin/codeproject.ai-server-2.9.4/runtimes/bin/ubuntu/python38/venv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: 'weights_only' is an invalid keyword argument for load()
08:04:02:Face Processing: Unable to load the face detector
08:04:02:Response rec'd from Face Processing command 'register' (...4dc1a1) ['Unable to load the face detector']

**Comment by ChrisMaunder** [comment]
Please try installing the latest 1.12.2 version
