### ISSUE TITLE
Failure on 2.9.5:  detect_adapter.py: ModuleNotFoundError: No module named 'codeproject_ai_sdk'

### ISSUE THREAD

**Issue by MichaelLuken** [codeproject/CodeProject.AI-Server#221]
**Area of Concern**
Windows 10 - install removing prior version:

11:38:59:Started Object Detection (YOLOv5 6.2) module
11:38:59:detect_adapter.py: Traceback (most recent call last):
11:38:59:detect_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ObjectDetectionYOLOv5-6.2\detect_adapter.py", line 19, in 
11:38:59:detect_adapter.py:     from codeproject_ai_sdk import JSON, ModuleRunner, LogMethod, LogVerbosity, RequestData
11:38:59:detect_adapter.py: ModuleNotFoundError: No module named 'codeproject_ai_sdk'
11:38:59:Module ObjectDetectionYOLOv5-6.2 has shutdown
11:38:59:detect_adapter.py: has exited

_________

Installation log:

11:17:46:System:           Windows
11:17:46:Operating System: Windows (Windows 10 Redstone)
11:17:46:CPUs:             Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (Intel)
11:17:46:                  1 CPU x 4 cores. 8 logical processors (x64)
11:17:46:GPU (Primary):    Intel(R) HD Graphics 530 (1,024 MiB) (Intel Corporation)
11:17:46:                  Driver: 31.0.101.2111
11:17:46:System RAM:       16 GiB
11:17:46:Platform:         Windows
11:17:46:BuildConfig:      Release
11:17:46:Execution Env:    Native
11:17:46:Runtime Env:      Production
11:17:46:Runtimes installed:
11:17:46:  .NET runtime:     9.0.0
11:17:46:  .NET SDK:         Not found
11:17:46:  Default Python:   Not found
11:17:46:  Go:               Not found
11:17:46:  NodeJS:           Not found
11:17:46:  Rust:             Not found
11:17:46:App DataDir:      C:\ProgramData\CodeProject\AI
11:17:46:Video adapter info:
11:17:46:  Intel(R) HD Graphics 530:
11:17:46:    Driver Version     31.0.101.2111
11:17:46:    Video Processor    Intel(R) HD Graphics Family
11:17:46:STARTING CODEPROJECT.AI SERVER
11:17:46:RUNTIMES_PATH             = C:\Program Files\CodeProject\AI\runtimes
11:17:46:PREINSTALLED_MODULES_PATH = C:\Program Files\CodeProject\AI\preinstalled-modules
11:17:46:DEMO_MODULES_PATH         = C:\Program Files\CodeProject\AI\src\demos\modules
11:17:46:EXTERNAL_MODULES_PATH     = C:\Program Files\CodeProject\CodeProject.AI-Modules
11:17:46:MODULES_PATH              = C:\Program Files\CodeProject\AI\modules
11:17:46:PYTHON_PATH               = \bin\windows\%PYTHON_NAME%\venv\Scripts\python
11:17:46:Data Dir                  = C:\ProgramData\CodeProject\AI
11:17:46:Server version:   2.9.5
11:17:50:Setting up initial modules. Please be patient...
11:17:50:Installing initial module ObjectDetectionYOLOv5Net.
11:17:50:Preparing to install module 'ObjectDetectionYOLOv5Net'
11:17:50:Downloading module 'ObjectDetectionYOLOv5Net'
11:17:51:Installing module 'ObjectDetectionYOLOv5Net'
11:17:51:ObjectDetectionYOLOv5Net:              Installing CodeProject.AI Analysis Module                
11:17:51:ObjectDetectionYOLOv5Net: ======================================================================
11:17:51:ObjectDetectionYOLOv5Net:                    CodeProject.AI Installer                           
11:17:51:ObjectDetectionYOLOv5Net: ======================================================================
11:17:52:Server: This is a new, unreleased version
11:17:57:ObjectDetectionYOLOv5Net: 37.8Gb of 939Gb available on OS (Windows 10 x86_64 - windows)
11:17:57:ObjectDetectionYOLOv5Net: General CodeProject.AI setup                                          
11:17:57:ObjectDetectionYOLOv5Net: Checking for VC++ Redist...v14 Present.
11:17:58:ObjectDetectionYOLOv5Net: Creating Directories...done
11:17:58:ObjectDetectionYOLOv5Net: GPU support                                                           
11:18:02:ObjectDetectionYOLOv5Net: CUDA Present...Yes (CUDA 11.7, cuDNN 8.7, CUDA Toolkit: true)
11:18:02:ObjectDetectionYOLOv5Net: Updating path to include cuDNN
11:18:02:ObjectDetectionYOLOv5Net: ROCm Present...No
11:18:02:ObjectDetectionYOLOv5Net: Checking for .NET 9.0...Checking runtimes...All good. Found .NET aspnetcore 9
11:18:05:ObjectDetectionYOLOv5Net: Reading ObjectDetectionYOLOv5Net settings.......done
11:18:05:ObjectDetectionYOLOv5Net: Installing module Object Detection (YOLOv5 .NET) 1.14.0 (Internal)    
11:18:12:ObjectDetectionYOLOv5Net: Downloading ObjectDetectionYOLOv5Net-DirectML-1.14.0.zip...Expanding...done.
11:18:16:ObjectDetectionYOLOv5Net: Copying contents of ObjectDetectionYOLOv5Net-DirectML-1.14.0.zip to bin...done
11:18:32:ObjectDetectionYOLOv5Net: Downloading YOLO ONNX models...Expanding...done.
11:18:32:ObjectDetectionYOLOv5Net: Copying contents of yolonet-models.zip to assets...done
11:18:42:ObjectDetectionYOLOv5Net: Downloading Custom YOLO ONNX models...Expanding...done.
11:18:42:ObjectDetectionYOLOv5Net: Copying contents of yolonet-custom-models.zip to custom-models...done
11:18:42:ObjectDetectionYOLOv5Net: Scanning modulesettings for downloadable models...No models specified
11:18:54:ObjectDetectionYOLOv5Net: ObjectDetectionYOLOv5Net module started.
11:18:57:ObjectDetectionYOLOv5Net: Self test: Self-test passed
11:18:58:ObjectDetectionYOLOv5Net: Module setup time 00:00:54.89
11:18:58:ObjectDetectionYOLOv5Net: Setup complete                                                        
11:18:58:ObjectDetectionYOLOv5Net: Total setup time 00:01:06.50
11:18:58:Module ObjectDetectionYOLOv5Net installed successfully.
11:18:58:Module ObjectDetectionYOLOv5Net not configured to AutoStart.
11:18:58:Installer exited with code 0
11:18:58:Installing initial module ObjectDetectionYOLOv5-6.2.
11:18:58:Preparing to install module 'ObjectDetectionYOLOv5-6.2'
11:18:58:Downloading module 'ObjectDetectionYOLOv5-6.2'
11:18:58:Installing module 'ObjectDetectionYOLOv5-6.2'
11:18:58:ObjectDetectionYOLOv5-6.2:              Installing CodeProject.AI Analysis Module                
11:18:58:ObjectDetectionYOLOv5-6.2: ======================================================================
11:18:58:ObjectDetectionYOLOv5-6.2:                    CodeProject.AI Installer                           
11:18:58:ObjectDetectionYOLOv5-6.2: ======================================================================
11:18:59:ObjectDetectionYOLOv5-6.2: 36.8Gb of 939Gb available on OS (Windows 10 x86_64 - windows)
11:18:59:ObjectDetectionYOLOv5-6.2: General CodeProject.AI setup                                          
11:18:59:ObjectDetectionYOLOv5-6.2: Checking for VC++ Redist...v14 Present.
11:18:59:ObjectDetectionYOLOv5-6.2: Creating Directories...done
11:18:59:ObjectDetectionYOLOv5-6.2: GPU support                                                           
11:19:00:ObjectDetectionYOLOv5-6.2: CUDA Present...Yes (CUDA 11.7, cuDNN 8.7, CUDA Toolkit: true)
11:19:00:ObjectDetectionYOLOv5-6.2: Updating path to include cuDNN
11:19:00:ObjectDetectionYOLOv5-6.2: ROCm Present...No
11:19:01:ObjectDetectionYOLOv5-6.2: Checking for .NET 9.0...Checking runtimes...All good. Found .NET aspnetcore 9
11:19:03:ObjectDetectionYOLOv5-6.2: Reading ObjectDetectionYOLOv5-6.2 settings.......done
11:19:03:ObjectDetectionYOLOv5-6.2: Installing module Object Detection (YOLOv5 6.2) 1.10.0 (Internal)     
11:19:03:ObjectDetectionYOLOv5-6.2: Installing Python 3.7
11:19:08:ObjectDetectionYOLOv5-6.2: Downloading Python 3.7 interpreter...Expanding...done.
11:20:22:ObjectDetectionYOLOv5-6.2: Creating Virtual Environment (Shared)...done
11:20:22:ObjectDetectionYOLOv5-6.2: Confirming we have Python 3.7 in our virtual environment...present
11:20:34:ObjectDetectionYOLOv5-6.2: Downloading Standard YOLO models...Expanding...done.
11:20:34:ObjectDetectionYOLOv5-6.2: Copying contents of models-yolo5-pt.zip to assets...done
11:20:48:ObjectDetectionYOLOv5-6.2: Downloading Custom YOLO models...Expanding...done.
11:20:49:ObjectDetectionYOLOv5-6.2: Copying contents of custom-models-yolo5-pt.zip to custom-models...done
11:20:49:ObjectDetectionYOLOv5-6.2: Installing Python packages for Object Detection (YOLOv5 6.2)
11:20:49:ObjectDetectionYOLOv5-6.2: [0;Installing GPU-enabled libraries: If available
11:20:50:ObjectDetectionYOLOv5-6.2: Ensuring Python package manager (pip) is installed...done
11:21:12:ObjectDetectionYOLOv5-6.2: Ensuring Python package manager (pip) is up to date...done
11:21:13:ObjectDetectionYOLOv5-6.2: Python packages specified by requirements.windows.cuda.txt
11:21:55:ObjectDetectionYOLOv5-6.2:   - Installing Pandas, a data analysis / data manipulation tool...(✅ checked) done
11:23:22:ObjectDetectionYOLOv5-6.2:   - Installing CoreMLTools, for working with .mlmodel format models...(✅ checked) done
11:23:39:ObjectDetectionYOLOv5-6.2:   - Installing OpenCV, the Open source Computer Vision library...(✅ checked) done
11:23:43:ObjectDetectionYOLOv5-6.2:   - Installing Pillow, a Python Image Library...(✅ checked) done
11:24:18:ObjectDetectionYOLOv5-6.2:   - Installing SciPy, a library for mathematics, science, and engineering...(✅ checked) done
11:24:19:ObjectDetectionYOLOv5-6.2:   - Installing PyYAML, a library for reading configuration files...Already installed
11:30:48:ObjectDetectionYOLOv5-6.2:   - Installing PyTorch, an open source machine learning framework...(✅ checked) done
11:38:58:Module ObjectDetectionYOLOv5-6.2 installed successfully.
11:38:58:Unable to install ObjectDetectionYOLOv5-6.2: Timed out attempting to install Module 'ObjectDetectionYOLOv5-6.2' (A task was canceled.)
11:38:58:ObjectDetectionYOLOv5-6.2:   - Installing TorchVision, for working with computer vision models...
11:38:59:
11:38:59:Module 'Object Detection (YOLOv5 6.2)' 1.10.0 (ID: ObjectDetectionYOLOv5-6.2)
11:38:59:Valid:            True
11:38:59:Module Path:      <root>\modules\ObjectDetectionYOLOv5-6.2
11:38:59:Module Location:  Internal
11:38:59:AutoStart:        True
11:38:59:Queue:            objectdetection_queue
11:38:59:Runtime:          python3.7
11:38:59:Runtime Location: Shared
11:38:59:FilePath:         detect_adapter.py
11:38:59:Start pause:      1 sec
11:38:59:Parallelism:      0
11:38:59:LogVerbosity:
11:38:59:Platforms:        all,!raspberrypi,!jetson
11:38:59:GPU Libraries:    installed if available
11:38:59:GPU:              use if supported
11:38:59:Accelerator:
11:38:59:Half Precision:   enable
11:38:59:Environment Variables
11:38:59:APPDIR             = <root>\modules\ObjectDetectionYOLOv5-6.2
11:38:59:CUSTOM_MODELS_DIR  = <root>\modules\ObjectDetectionYOLOv5-6.2\custom-models
11:38:59:MODELS_DIR         = <root>\modules\ObjectDetectionYOLOv5-6.2\assets
11:38:59:MODEL_SIZE         = Medium
11:38:59:USE_CUDA           = True
11:38:59:YOLOv5_AUTOINSTALL = false
11:38:59:YOLOv5_VERBOSE     = false
11:38:59:
11:38:59:Started Object Detection (YOLOv5 6.2) module
11:38:59:detect_adapter.py: Traceback (most recent call last):
11:38:59:detect_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ObjectDetectionYOLOv5-6.2\detect_adapter.py", line 19, in 
11:38:59:detect_adapter.py:     from codeproject_ai_sdk import JSON, ModuleRunner, LogMethod, LogVerbosity, RequestData
11:38:59:detect_adapter.py: ModuleNotFoundError: No module named 'codeproject_ai_sdk'
11:38:59:Module ObjectDetectionYOLOv5-6.2 has shutdown
11:38:59:detect_adapter.py: has exited

**Comment by MichaelLuken** [comment]
I tried re-installing just YOLOv5-6.2 and it worked.  Appears all OK now

**Comment by ChrisMaunder** [comment]
"11:38:58:Unable to install ObjectDetectionYOLOv5-6.2: Timed out attempting to install Module 'ObjectDetectionYOLOv5-6.2' (A task was canceled.)" That seems to be the problem. Glad a re-install fixed the issue.
