### ISSUE TITLE
Object Detection(YOLO) Custom-Models

### ISSUE THREAD

**Issue by ryfon** [codeproject/CodeProject.AI-Server#23]
Yolo updated .pt format and all newly trained models no longer work.
Giving error:
(Can't get attribute 'DetectionModel' on )

After updating to newest yolov5, only notable change needed was in process.py
line 10 scale_coords, -> scale_boxes,
line 119 pred[:, :4] = scale_coords(img.shape[2:], pred[:, :4], img0.shape).round() -> pred[:, :4] = scale_boxes(img.shape[2:], pred[:, :4], img0.shape).round()

**Comment by ChrisMaunder** [comment]
We've updated the next release with the latest YOLO code
