### ISSUE TITLE
Constant external download traffic, v2.9.5, from 185.199.109.153

### ISSUE THREAD

**Issue by epc002** [codeproject/CodeProject.AI-Server#235]
Recently +updated from 2.6.5 to 2.9.5, and am noticing that when the CPAI dashboard is open there is constant external WAN network traffic, approx 250kbps download and 50kbps upload. Closing the dashboard and it goes away. Anyone know what this traffic is for and why it is necessary?

see also  https://github.com/codeproject/CodeProject.AI-Server/discussions/234#discussioncomment-11569342

**Comment by epc002** [comment]
fixed 
https://github.com/codeproject/CodeProject.AI-Server/discussions/234#discussioncomment-11585017

**Comment by ChrisMaunder** [comment]
Additional info: unchecking the "check for updates" control on the modules tab will stop the traffic
