### ISSUE TITLE
Dog not detected

### ISSUE THREAD

**Issue by weswitt** [codeproject/CodeProject.AI-Server#25]
In the image below my dog is detected as a person.

**Your System:**
 - CodeProject.AI Server version: 1.5.6-Beta+0002
 - OS: Windows 10
 - System RAM: 32gb
 - GPU: none, CPU only
 - GPU RAM: none

![image](https://user-images.githubusercontent.com/15125944/196993730-bef04ff1-c313-4a0f-84a7-bb2a02c5eacc.png)

**Comment by ChrisMaunder** [comment]
Don't dogs consider themselves people?

We're going to be embarking on a project to improve the models.

**Comment by weswitt** [comment]
thanks.  i know that the code is under development and constant improvement and thanks for the work. just wanted to report what i see and provide an image that can be used for testing.

**Comment by ChrisMaunder** [comment]
Thank you!

**Comment by MikeLud** [comment]
@weswitt what model were you using?

**Comment by MikeLud** [comment]
@ChrisMaunder I have an idea on how to element false positives. We could do something like the face detection module where you register the false positives. So as users gets the false positives they can register it with the corrected label.

**Comment by weswitt** [comment]
> @weswitt what model were you using?

not sure that i have any control over the model. i'm using this inside blueiris.

**Comment by MikeLud** [comment]
@weswitt most likely then you are using the default YOLO model. Below is a list of custom models that are installed with CodeProject.AI and what they detect.
If you what to try one of the custom models below are screenshot with settings for using the ipcam-general custom model

# CodeProject.AI-Custom-IPcam-Models

**IPcam-combined Labels:**
    - person, bicycle, car, motorcycle, bus, truck, bird, cat, dog, horse, sheep, cow, bear, deer, rabbit, raccoon, fox, skunk, squirrel, pig

**IPcam-general Labels (includes dark models images):**
    - person, vehicle

**IPcam-animal Labels:**
    - bird, cat, dog, horse, sheep, cow, bear, deer, rabbit, raccoon, fox, skunk, squirrel, pig

**IPcam-dark Labels:**
    - Bicycle, Bus, Car, Cat, Dog, Motorcycle, Person

# Main AI settings
![image](https://user-images.githubusercontent.com/36526272/197057080-f01363d2-6465-4d15-894e-e18fe8389ecc.png)

# Camera AI settings
![image](https://user-images.githubusercontent.com/36526272/197057408-379ea637-85a9-425e-b053-3a8415c6e506.png)

**Comment by ChrisMaunder** [comment]
Closing this since it requires an update to the trained models (ie it's a data/model issue not a code / server issue). We'll be tackling these issues directly in future updates.
