### ISSUE TITLE
GPU Not Being Used

### ISSUE THREAD

**Issue by weswitt** [codeproject/CodeProject.AI-Server#26]
I just installed a GTX 1060 for use by AP.AI. I followed the instructions to install all the CUDA stuff. The dashboard reports that only the portrait filter is using the GPU.  Is there a config step that I missed?

Your System:
CodeProject.AI Server version: 1.6.7-Beta
OS: Windows 10
System RAM: 32gb
GPU: GTX 1060
GPU RAM: 6GB

![image](https://user-images.githubusercontent.com/15125944/197071300-5ee9ed4e-5831-437d-80f8-a17501ea66a0.png)

**Comment by weswitt** [comment]
This might be relevant

![image](https://user-images.githubusercontent.com/15125944/197071721-52baf0e0-b518-4182-8545-8e39fc0fda40.png)

**Comment by weswitt** [comment]
and the hardware info:

Name: Microsoft Remote Display Adapter
-----------------------------------------------------------------------------------
Accelerator Capabilities
Adapter Compatibility              Microsoft
Adapter DAC Type
Adapter RAM
Availability                       3
Capability Descriptions
Caption                            Microsoft Remote Display Adapter
Color Table Entries
Config Manager Error Code          0
Config Manager User Config         False
Creation Class Name                Win32_VideoController
Current Bits Per Pixel             32
Current Horizontal Resolution      1920
Current Number Of Colors           4294967296
Current Number Of Columns          0
Current Number Of Rows             0
Current Refresh Rate               32
Current Scan Mode                  4
Current Vertical Resolution        1200
Description                        Microsoft Remote Display Adapter
Device ID                          VideoController1
Device Specific Pens
Dither Type                        0
Driver Date                        20060621000000.000000-000
Driver Version                     10.0.19041.2075
Error Cleared
Error Description
ICM Intent
ICM Method
Inf Filename                       rdpidd.inf
Inf Section                        RdpIdd_Install.NT
Install Date
Installed Display Drivers
Last Error Code
Max Memory Supported
Max Number Controlled
Max Refresh Rate                   32
Min Refresh Rate                   32
Monochrome                         False
Number Of Color Planes
Number Of Video Pages
PNP Device ID                      SWD\REMOTEDISPLAYENUM\RDPIDD_INDIRECTDISPLAY&SESSIONID_0002
Power Management Capabilities
Power Management Supported
Protocol Supported
Reserved System Palette Entries
Specification Version
Status                             OK
Status Info
System Creation Class Name         Win32_ComputerSystem
System Palette Entries
Time Of Last Reset
Video Architecture                 5
Video Memory Type                  2
Video Mode
Video Mode Description             1920 x 1200 x 4294967296 colors
Video Processor

Name: Intel(R) UHD Graphics 630
-----------------------------------------------------------------------------------
Accelerator Capabilities
Adapter Compatibility              Intel Corporation
Adapter DAC Type                   Internal
Adapter RAM                        1073741824
Availability                       3
Capability Descriptions
Caption                            Intel(R) UHD Graphics 630
Color Table Entries
Config Manager Error Code          0
Config Manager User Config         False
Creation Class Name                Win32_VideoController
Current Bits Per Pixel             32
Current Horizontal Resolution      1920
Current Number Of Colors           4294967296
Current Number Of Columns          0
Current Number Of Rows             0
Current Refresh Rate               59
Current Scan Mode                  4
Current Vertical Resolution        1200
Description                        Intel(R) UHD Graphics 630
Device ID                          VideoController2
Device Specific Pens
Dither Type                        0
Driver Date                        20220719000000.000000-000
Driver Version                     31.0.101.2111
Error Cleared
Error Description
ICM Intent
ICM Method
Inf Filename                       oem18.inf
Inf Section                        iCML_w10_DS
Install Date
Installed Display Drivers          C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd12umd64.dll
Last Error Code
Max Memory Supported
Max Number Controlled
Max Refresh Rate                   60
Min Refresh Rate                   59
Monochrome                         False
Number Of Color Planes
Number Of Video Pages
PNP Device ID                      PCI\VEN_8086&DEV_9BC5&SUBSYS_86941043&REV_05\3&11583659&0&10
Power Management Capabilities
Power Management Supported
Protocol Supported
Reserved System Palette Entries
Specification Version
Status                             OK
Status Info
System Creation Class Name         Win32_ComputerSystem
System Palette Entries
Time Of Last Reset
Video Architecture                 5
Video Memory Type                  2
Video Mode
Video Mode Description             1920 x 1200 x 4294967296 colors
Video Processor                    Intel(R) UHD Graphics Family

Name: NVIDIA GeForce GTX 1060 6GB
-----------------------------------------------------------------------------------
NVIDIA-SMI Version                 522.25
NVIDIA Driver Version              522.25
CUDA Tools Version                 11.8

Accelerator Capabilities
Adapter Compatibility              NVIDIA
Adapter DAC Type                   Integrated RAMDAC
Adapter RAM                        -1048576
Availability                       8
Capability Descriptions
Caption                            NVIDIA GeForce GTX 1060 6GB
Color Table Entries
Config Manager Error Code          0
Config Manager User Config         False
Creation Class Name                Win32_VideoController
Current Bits Per Pixel
Current Horizontal Resolution
Current Number Of Colors
Current Number Of Columns
Current Number Of Rows
Current Refresh Rate
Current Scan Mode
Current Vertical Resolution
Description                        NVIDIA GeForce GTX 1060 6GB
Device ID                          VideoController3
Device Specific Pens
Dither Type
Driver Date                        20221006000000.000000-000
Driver Version                     31.0.15.2225
Error Cleared
Error Description
ICM Intent
ICM Method
Inf Filename                       oem10.inf
Inf Section                        Section024
Install Date
Installed Display Drivers          C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll
Last Error Code
Max Memory Supported
Max Number Controlled
Max Refresh Rate
Min Refresh Rate
Monochrome                         False
Number Of Color Planes
Number Of Video Pages
PNP Device ID                      PCI\VEN_10DE&DEV_1C03&SUBSYS_61633842&REV_A1\4&38AB2860&0&0008
Power Management Capabilities
Power Management Supported
Protocol Supported
Reserved System Palette Entries
Specification Version
Status                             OK
Status Info
System Creation Class Name         Win32_ComputerSystem
System Palette Entries
Time Of Last Reset
Video Architecture                 5
Video Memory Type                  2
Video Mode
Video Mode Description
Video Processor                    NVIDIA GeForce GTX 1060 6GB

**Comment by MikeLud** [comment]
It looks to be enabled, but try clicking on the three dots on the right side of the module then click on Half Precision then Disable. If that does not work then try Enable GPU

![image](https://user-images.githubusercontent.com/36526272/197079373-a3c98768-dd43-4050-bda2-f33d00ca072f.png)


![image](https://user-images.githubusercontent.com/36526272/197078185-499d96d6-55e8-404b-994e-23c5362e2679.png)

**Comment by weswitt** [comment]
no joy. that did not make it switch over to GPU.

**Comment by weswitt** [comment]
i cranked up the logging level. i see the following in the log. why would this be the case?

2022-10-21 12:25:35: Server: detect_adapter.py: use_CUDA:    False in Server

**Comment by weswitt** [comment]
Is CUDA 11.7 required or will 11.8 work? I ask because 11.7 is no longer available so I installed 11.8. Wondering of this is a cause of the issue?

**Comment by weswitt** [comment]
> Is CUDA 11.7 required or will 11.8 work? I ask because 11.7 is no longer available so I installed 11.8. Wondering of this is a cause of the issue?

OK, I found an archived 11.7.1 version of CUDA.  Do I need to uninstall 11.8 and install 11.7.1?

**Comment by MikeLud** [comment]
11.8 might be the issue since the code was developed around 11.7 so go back one more version to 11.7 and uninstall 11.8

https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by weswitt** [comment]
ok i uninstalled cuda 11.8 and installed 11.7.  so now i'm certain that everything that is installed matches the required versions. yet object detection will not use the gpu.  what can be done to diagnose this issue?

**Comment by MikeLud** [comment]
Might need @ChrisMaunder to look at this issue for you

**Comment by weswitt** [comment]
i seem to have solved this. i decided to start from scratch so i clean installed windows and everything else. viola! i now have the gpu processing for cp.ai. my processing times are WAY better now too.

i think that what happened is that with all the installing & uninstalling something got jacked up and the only way to fix it was to nuke the machine and start over.

**Comment by MikeLud** [comment]
@weswitt did you get it to work with CUDA 11.8 or 11.7?

**Comment by weswitt** [comment]
i used the documented 11.7 and associated dependencies.

**Comment by weswitt** [comment]
the other thing of note for others is to watch out for windows auto driver install dance. it will jack things up and install a newer nvidia display driver that uses 11.8.  to avoid this after a clean windows install just unplug the network cable before booting and install the correct driver that uses 11.7 (you can download the driver package on another pc and shuttle it over using a usb thumb drive).

**Comment by ChrisMaunder** [comment]
We'll see what we can do about warning about this and/or adapting to 11.8. Our system needs to work with whatever everyone has installed.

Thanks for being patient with this.

**Comment by weswitt** [comment]
no problem at all. i'm just happy that i got it working. thanks for the work on this project.

**Comment by MikeLud** [comment]
@ChrisMaunder I am seeing another user have issues getting CUDA to work with CUDA 11.8. You want to update the link for CUDA 11.7 to the below link.

https://developer.nvidia.com/cuda-11-7-0-download-archive
![image](https://user-images.githubusercontent.com/36526272/197763279-52cca114-49d8-41ae-a501-541074959a87.png)

**Comment by ChrisMaunder** [comment]
Thanks for that. I've updated the text in the article to be more accurate and provided a link to the "old" versions.

We'll have to test and update the code to work with 11.8.

I thought point releases were meant to be backwards compatible. 🙄
