### ISSUE TITLE
Installation issue on windows 10 x64

### ISSUE THREAD

**Issue by msaaqibkhan** [codeproject/CodeProject.AI-Server#30]
- [ ] Installer
- [ ] Runtime [e.g. Pythohn3.7, .NET]

I am trying to install the server (CodeProject.AI.Server-1.6.8.0.exe) on my laptop having Windows 10 x64.
But the installer setup stuck at this screen:
![image](https://user-images.githubusercontent.com/12228617/203112584-28ad704f-1a66-4133-801e-25fbdd76e240.png)
#

I have tried many times but it doesn't move forward.
Even I have disabled my Virus & threat protection settings but no luck.
I am sure the issue persist in my PC because the same setup was installed on another PC where I just installed for testing purpose but it's not being installed on my PC.

Please help.

  - OS: Windows x64
 - System RAM 12Gb

**Comment by ChrisMaunder** [comment]
A dumb question, but are you connected to the internet when you run the installer?

**Comment by msaaqibkhan** [comment]
Yes,
I am connected to the internet

**Comment by ChrisMaunder** [comment]
Have you tried running the installer under Admin rights?

**Comment by msaaqibkhan** [comment]
Yes, every time I run as administrator.
Every time it stuck and I have to Cancel the setup after waiting for a long time.
Setup ended with this screen:
![image](https://user-images.githubusercontent.com/12228617/203114811-f4095f31-8125-416a-a9e3-a11d7fbfdd58.png)
  
here is the link of log file:
https://drive.google.com/file/d/1-63EF8rRWeU8xcQ_vAwgVoiEgFq42p-h/view?usp=share_link

**Comment by ChrisMaunder** [comment]
> Failed to acquire payload from: 'https://codeproject-ai.s3.ca-central-1.amazonaws.com/sense/installer/version-1.6.8.0/Python37.Installer-1.6.8.0.msi' to working path: 'C:\Users\Saqib\AppData\Local\Temp\{BBC74C23-07FA-485E-B11D-868B7D14B960}\CODEPROJECTAIPYTHON37'

So it looks like you're unable to reach our S3 bucket. I've confirmed this item has public access. Can you please try downloading https://codeproject-ai.s3.ca-central-1.amazonaws.com/sense/installer/version-1.6.8.0/Python37.Installer-1.6.8.0.msi directly to see if there is any issue with your connection to AWS

**Comment by zombu2** [comment]
I'm having the same issue accessing the aws server it mostly just times out but once every 50 or so times it actually starts downloading the server stopper and sometimes even makes it to python but then suddenly times out with an unspecified error 
looking at the logs it just says timed out so there is something going on with aws

also trying to download the msi package in a browser mostly ends up with a connection reset 
ive tried it in multiple locations same issue

**Comment by ChrisMaunder** [comment]
This is an issue with AWS. I'm afraid this isn't something we can address in code. The only option which we may look to addressing in the future is to provide fallback download locations.
