### ISSUE TITLE
Unhandled exception on start up 2.0.6 

### ISSUE THREAD

**Issue by metricconversion** [codeproject/CodeProject.AI-Server#33]
**Area of Concern**
- [x ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Install completes with no issues, but the service won't start, and I can't manually run the codeproject.ai.server.exe from elevated command prompt.

![image](https://user-images.githubusercontent.com/10645276/214632737-79e58ce8-bd67-4e76-bced-bd9df980a27d.png)

[Log files](https://drive.google.com/drive/folders/19wy5S0KUNcq4wtPlQ7Gyq_H3hauGw5kN?usp=sharing)

There only file in the C:\ProgramData\CodeProject\AI\ is the setup.bat

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.0.6
 - OS: Win 10 22H2
 - System RAM 16GB
 - GPU (if available) on CPU Intel HD Graphics

**Additional context**
I've attempted to install the 1.5.6 version I had working before but that has the same issue also.

**Comment by matthewDDennis** [comment]
It looks like your install is REALLY messed up.
I recommend reinstalling the app by
- [ ] Using the Services app to stop CodeProject.AI Server
- [ ] Use the Task Manager to kill any Python commands running
- [ ] Use the Task Manager to kill ObjectDetectionNet if running
- [ ] Uninstall the CodeProject.AI Server app
- [ ] Delete the  C:\ProgramData\CodeProject\AI directory if it exists
- [ ] Delete the  C:\Priogram Files\CodeProject\AI directory if it exists

You should now be in a state to reinstall 2.0.6

**Comment by metricconversion** [comment]
Heartily agree! 
I've uninstalled, restarted, and reinstalled fresh about 5 times now.

**Comment by metricconversion** [comment]
Oh my word I realized I've been looking past the "ProgramData" and reading it as "Program Files" this whole time. Literally took you breaking it out into two different steps for me to register. 

Once I deleted the ProgramData\CodeProject\AI directory and reinstalled that was literally all it took. 

Thanks for detailing that out!
