### ISSUE TITLE
Error upon installing via docker

### ISSUE THREAD

**Issue by deboy69** [codeproject/CodeProject.AI-Server#34]
Infor ** Operating System: Linux (Linux 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022)
Infor ** Architecture:     x64
Infor ** Target:           Linux
Infor ** BuildConfig:      Release
Infor ** Execution Env:    Docker
Infor ** Runtime Env:      Production
Infor ** App DataDir:      /etc/codeproject/ai
Infor 
Debug ------------------------------------------------------------------
Debug ROOT_PATH               = /app
Debug MODULES_PATH            = /app/AnalysisLayer
Debug DOWNLOADED_MODULES_PATH = /app/modules
Debug PYTHON_BASEPATH         = /app/AnalysisLayer/bin/%PYTHON_RUNTIME%/venv
Debug PYTHON_PATH             = %PYTHON_RUNTIME%
Debug Temp Dir:                /tmp/
Debug Data Dir:                /etc/codeproject/ai
Debug ------------------------------------------------------------------
Infor ModuleRunner Start
Warni Overriding address(es) 'http://+:32168, http://+:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Error BackgroundService failed
Unable to start the server: Address family not supported by protocol.
Check that another instance is not running on the same port.
Press Enter to close.eInfor ** Operating System: Linux (Linux 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022)

**Comment by vajonam** [comment]
This is an issue with IPV6, if you dont have it the current image doesn't startup. setting `-p 0.0.0.0:32168:32168` doesn't fix it that works for other images. need an option to disable ipv6

**Comment by vajonam** [comment]
https://github.com/codeproject/CodeProject.AI-Server/blob/25e165e8e89bfe83020caf826519ef1af21a4a1b/src/API/Server/FrontEnd/Program.cs#L549 specifically looking for IPv6.

**Comment by vajonam** [comment]
Maybe `IPAddress.Any` will help?

**Comment by ChrisMaunder** [comment]
We will add an option to select IP4 and/or IP6
