### ISSUE TITLE
Logs filled : Cause=No internet accès

### ISSUE THREAD

**Issue by MrSiO** [codeproject/CodeProject.AI-Server#35]
**Area of Concern**
- [X] Server

**Describe the bug**
Yesterday I installed (via Docker-Compose) the latest senseIA container (codeproject/ai-server:latest) in a closed environment meaning the container has **no** internet access by default (only on demand/manual authorization).

This causes the logs to be filled with:  
`Error checking for available modules: The request was canceled due to the configured HttpClient`

**Expected behavior**
Since i'm using Watchtower, I expect to disable the server auto-update feature and let Watchtower update when needed.

**Your System (please complete the following information):**
```
CodeProject.AI Server version:  2.0.7
Operating System: Linux (Linux 5.4.0-137-generic #154-Ubuntu)
CPUs:             1 CPU x 2 cores. 4 logical processors (x64)
System RAM:       8 GiB
Target:           Linux
BuildConfig:      Release
Execution Env:    Docker
Runtime Env:      Production
.NET framework:   .NET 7.0.2
System GPU info:
  GPU 3D Usage       0%
  GPU RAM Usage      0

```
**Additional context**
Using senseAI to replace DeepStack on my iSpyAgentDVR installation.
Seems to be working fine (might be a little slow... 736 ms) but definitely the logs pollution is affecting troubleshooting.

Thx!!

**Comment by MrSiO** [comment]
Could you provide destination URL and ports so firewall exceptions can be opened to give limited internet access to senseAI?

Thx

**Comment by jinja2ninja** [comment]
I seem to be getting a similar issue (although not behind a restrictive firewall). It seems like a feature to disable this check would be really nice
```
Error Error checking for latest version: Resource temporarily unavailable (www.codeproject.com:443)
```

**Comment by MrSiO** [comment]
Yes.

Add a manual update option and give the ability to disable automatic update
maybe...

**Comment by jinja2ninja** [comment]
I'm not sure if it would work for our purposes or not, but there does appear to be an option to run it offline on line 82 of [this file](https://github.com/codeproject/CodeProject.AI-Server/blob/main/src/setup.sh)
I'm going to play around with building a docker image with that set to `true` and see if that makes any difference.

**Comment by ChrisMaunder** [comment]
Reducing the noise from this check is in place for the next version. There is also a setting in the appsettings file in the Server's folder:
```jsonc
  "Logging": {
    "AIServer": {
      "MaxLogsToStoreMB": 20, // Maximum amount of logs to store in MB. Once this is hit old log files get dumped (not trimmed, dumped)
...
```
