### ISSUE TITLE
Release 2.0.8 - no prediction object available when no face found

### ISSUE THREAD

**Issue by elad-bar** [codeproject/CodeProject.AI-Server#39]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Since v2.0.8, when no face detected, prediction property is not available, breaking change

**Expected behavior**
Empty array as it was before, 0 items in array self explains that no face found

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.0.8
 - OS: Ubuntu 20.04
 - System RAM 96GB
 - GPU GeForce RTX 2070
 - GPU RAM 6GB

**Comment by ChrisMaunder** [comment]
This was a bug and has been fixed in the next release. In recognise_face it should be

```python
if found_face == False:
    output = {"success": False, "error": "No face found in image", "inferenceMs": inferenceMs}
```
