### ISSUE TITLE
Unnecessary IO activity on Windows

### ISSUE THREAD

**Issue by janost** [codeproject/CodeProject.AI-Server#43]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Running the AI server on Windows causes seemingly unnecessary IO activity. I observed that while the server is running and processing requests it writes a lot of temporary files to the `C:\Windows\SystemTemp\ASPNETCORE_<uuid>.tmp` path. Seemingly these are images, probably request bodies being buffered to the disk. This behaviour doesn't seem to be specific to any module, so I assume the server itself is doing this. If I stop the server the observed IO activity stops immediately.

**Expected behavior**
Server should not buffer request bodies to temporary files or the server should provide an option to use memory for buffering requests.

**Screenshots**
![Screenshot from 2023-04-07 19-50-39](https://user-images.githubusercontent.com/11500057/230661504-c405fb49-93ec-46a2-b186-9b1a5056d8e4.png)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.0.8-beta
 - OS: Windows Server 2022 21H2
 - System RAM: 16 GiB
 - GPU: Intel HD 530
 - GPU RAM: ?

**Additional context**
This seems to be an ASP.NET (default?) behaviour ([see here](https://stackoverflow.com/questions/62910894/asp-net-core-writes-request-body-to-windows-temp-folder)), although I'm completely clueless about ASP.NET.

**Comment by ChrisMaunder** [comment]
This is part of the ASP.NET infrastructure. Are the files remaining in the temp directory, or are they being cleaned automatically?

**Comment by janost** [comment]
They are being cleaned up, so that's not an issue. In my use case there are several GiBs of images being processed daily doing a small amount of additional wear on the SSD.
