### ISSUE TITLE
Request: Adding AMD EOCm HIP Support

### ISSUE THREAD

**Issue by Dvalin21** [codeproject/CodeProject.AI-Server#46]
Requesting to add AMD EOCm HIP Support (AMD's version of CUDA)

I have a AMD RX 5500XT GPU and unable to use it with CodeProject.AI. I did noticed that Google Coral support is being worked on, but not sure if I would benefit more with the GPU than I would with the Google Coral.

[AMD EOCm HIP](https://www.google.com/search?q=AMD+EOCm+HIP&oq=AMD+EOCm+HIP&aqs=chrome..69i57j33i160l3.7202j0j9&sourceid=chrome&ie=UTF-8)

**Comment by matthewDDennis** [comment]
What OS are you running on.  If Windows, the Object Detection (YOLOV5 NET) uses DirectML, which in turn uses DirectX to process the AI Models.  Because of this, it works with a broad range of GPUs, including AMD.

**Comment by Dvalin21** [comment]
> What OS are you running on. If Windows, the Object Detection (YOLOV5 NET) uses DirectML, which in turn uses DirectX to process the AI Models. Because of this, it works with a broad range of GPUs, including AMD.

Linux Ubuntu Server

**Comment by Dvalin21** [comment]
Thanks for the update. Let me know if I can test anything for you. I have a
AMD 5500xt.
