### ISSUE TITLE
Failed to create CoreCLR, HRESULT 0x80070008

### ISSUE THREAD

**Issue by etlweather** [codeproject/CodeProject.AI-Server#47]
**Area of Concern**
- [x ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
I run the docker version using the command from the documentation:

```
docker run --name CodeProject.AI -d -p 32168:32168 codeproject/ai-server
```

And I get "Failed to create CoreCLR, HRESULT 0x80070008"

**Expected behavior**
I would expect it to actual start as covered in the documentation.

**Screenshots**
N/A

**Your System (please complete the following information):**
 - CodeProject.AI Server version: docker image latest
 - OS: Ubuntu 20.04
 - System RAM 96GB
 - GPU none
 - GPU RAM N/A

**Additional context**
Tried it on two computer, got same results.

**Comment by ChrisMaunder** [comment]
This could be to do with https://docs.linuxserver.io/faq#jammy

**Comment by etlweather** [comment]
That was it. Thank you!
