### ISSUE TITLE
Windows Service won't Start

### ISSUE THREAD

**Issue by dsw-solutions** [codeproject/CodeProject.AI-Server#48]
**Area of Concern**
- [ x] Server

**Describe the bug**
After an install of 2.0.8 on Windows the CodeProject.AI Server won't start. I tried uninstalling and reinstalling and same issue. There also doesn't appear to be a way to change the install location.

**Expected behavior**
The services starts and stays running.

**Screenshots**
![image](https://user-images.githubusercontent.com/67870268/233472944-9ac6d073-97c5-4e84-ba44-bf9599ce9017.png)
![image](https://user-images.githubusercontent.com/67870268/233475279-0d9bd511-be25-4b7e-8f9b-8549b24c2aa4.png)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.08
 - OS: Windows 10
 - System RAM: 64GB
 - CPU: i9-12900K

**Comment by dsw-solutions** [comment]
Is the default port 5000 or 32168? I have another service already using port 5000 and if I disable that then it works.

**Comment by ChrisMaunder** [comment]
The default is 32168, but 5000 is enabled for legacy apps. We recommend using 32168 to avoid the types of conflicts you see.

**Comment by dsw-solutions** [comment]
> The default is 32168, but 5000 is enabled for legacy apps. We recommend using 32168 to avoid the types of conflicts you see.

How do you disable it from listening on 5000?
Thanks
