### ISSUE TITLE
Errors When Opening with Visual Studio 2022

### ISSUE THREAD

**Issue by MaxFun** [codeproject/CodeProject.AI-Server#49]
When opening unzipped CodeProject.AI Server from https://github.com/codeproject/CodeProject.AI-Server with Visual Studio 2022 downloaded 4/21/23 7:12am, it required modification to open. After opening, a migration report was generated with 7 errors. See attached report.

**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

**Expected behavior**

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 
 - OS: [e.g. Ubuntu 20.04]
 - System RAM [e.g. 16Gb]
 - GPU (if available) [e.g. GeForce RTX 3060]
 - GPU RAM (if available)  [e.g. 4Gb]

**Additional context**
[VS2022 Migration Report 4-21-23.pdf](https://github.com/codeproject/CodeProject.AI-Server/files/11296530/VS2022.Migration.Report.4-21-23.pdf)

**Comment by ChrisMaunder** [comment]
Sorry - wrong .sln file was included in that repo. Fixed.
