### ISSUE TITLE
Missing dockerfiles for project

### ISSUE THREAD

**Issue by PatrickBig** [codeproject/CodeProject.AI-Server#51]
I was looking into this project and I noticed that there does not seem to be any dockerfiles in this repository for the images that are pushed.

Where are they located? I searched this organization and was not able to locate them.

**Comment by PrplHaz4** [comment]
Wondering the same - I wanted to try and figure out what (if anything) is included in the amd64 builds for Coral TPUs.  Having dockerfiles available would also give the community a much easier way to contribute.

**Comment by ChrisMaunder** [comment]
They are in a different repo from this one. No decision yet if we'll pull them into this repo.
