### ISSUE TITLE
Module ALPR installation does not work - 'Error: you have urllib3 2.0.3 which is incompatible' and ALPR shuts down

### ISSUE THREAD

**Issue by inspired27** [codeproject/CodeProject.AI-Server#52]
Please can someone help this is a genuine issue cannot install ALPR properly inside Docker on Linux.

I managed to execute the ./../../setup.sh from inside ALPR directory in Linux docker however getting error "you have urllib3 2.0.3 which is incompatible" during install. Also ALPR starts then immediately shuts down:

**Install Log:**

`Setting up CodeProject.AI Development Environment

======================================================================

               CodeProject.AI Installer                           
======================================================================

Checking GPU support

CUDA Present...No
Allowing GPU Support: Yes
Allowing CUDA Support: Yes

General CodeProject.AI setup

Creating Directories...Done

Installing module ALPR

Python 3.8 is already installed
Virtual Environment already present
Checking for Python 3.8...Found Python 3.8.16. present
Checking for CUDA...Not found
Ensuring PIP is installed...Done
Updating PIP...Done
Installing setuptools...Done
Choosing packages from requirements.linux.txt
Installing Packages into Virtual Environment...**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.29.135 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.3 which is incompatible.
google-auth 2.18.0 requires urllib3<2.0, but you have urllib3 2.0.3 which is incompatible.
Success**
Checking for CUDA...Not found
Ensuring PIP is installed...Done
Updating PIP...Done
Installing setuptools...Done
Choosing packages from requirements.txt
Installing Packages into Virtual Environment...**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.29.135 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.3 which is incompatible.
google-auth 2.18.0 requires urllib3<2.0, but you have urllib3 2.0.3 which is incompatible.**
Success
Downloading OCR models... already exists...Expanding...Done.
Applying PaddleOCR patch
Module setup complete   
                              `
**Server Log:**

**Log ALPR Starts Up and Immediately Shuts down.**

23:22:44:Command: /app/modules/ALPR/bin/linux/python38/venv/bin/python3
23:22:44:Starting /app...es/ALPR/bin/linux/python38/venv/bin/python3 "/app/modules/ALPR/ALPR_adapter.py"
23:22:44:
23:22:44:Attempting to start ALPR with /app/modules/ALPR/bin/linux/python38/venv/bin/python3 "/app/modules/ALPR/ALPR_adapter.py"
23:22:44:
23:22:44:Module 'License Plate Reader' (ID: ALPR)
23:22:44:Module Path: /app/modules/ALPR
23:22:44:AutoStart: True
23:22:44:Queue: alpr_queue
23:22:44Platforms: windows,linux,macos,macos-arm64
23:22:44:GPU: Support disabled
23:22:44:parallelism: 0
23:22:44:Accelerator:
23:22:44:Half Precis.: enable
23:22:44:Runtime: python38
23:22:44:Runtime Loc: Local
23:22:44:FilePath: ALPR_adapter.py
23:22:44:pre installed: False
23:22:44:Start pause: 1 sec
23:22:44:LogVerbosity:
23:22:44:Valid: True
23:22:44:Environment Variables
23:22:44:AUTO_PLATE_ROTATE = True
23:22:44:pLATE_CONFIDENCE = 0.7
23:22:44:pLATE_RESCALE_FACTOR = 2
23:22:44:pLATE_ROTATE_DEG = 0
23:22:44:
23:22:44:Started License Plate Reader module
**23:22:45:Module ALPR has shutdown**

**Comment by crazyfrog-github** [comment]
Please can someone help this is a proper issue cannot install ALPR properly on Windows or inside Docker on Linux or Windows.

Please can you provide the commands to execute the installation script for ALPR inside docker under Exec please it says permission denied when trying to run ./install.sh inside the /app/modules/ALPR directory as root.

**Comment by ChrisMaunder** [comment]
The urllib error can be safely ignored. That library isn't used.

Can you please try uninstalling then reinstalling the ALPR module via the dashboard?
