### ISSUE TITLE
Can we train the models ourselves?

### ISSUE THREAD

**Issue by erikshelley** [codeproject/CodeProject.AI-Server#53]
This is not a bug, just a question and an image with few classification examples I thought were entertaining. I've noticed the ipcam-combined model often misidentifies animals in my yard. Can I train the model on these misidentified images to create my own custom version of the model? If it is possible I would appreciate it if you could point me in the right direction to get started (links, tools, terminology, etc).

Thanks for the great project. I'm really enjoying it.

![Mystery-Creature](https://github.com/codeproject/CodeProject.AI-Server/assets/39465362/69e632b6-ecde-4373-9deb-96a63742326d)

**Comment by MikeLud** [comment]
Below is a link on how to train custom models using YOLOv5

https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/

**Comment by MikeLud** [comment]
@erikshelley also here is another link on how to train custom models using YOLOv5 that @matthewDDennis wrote.

https://www.codeproject.com/Articles/5347827/How-to-Train-a-Custom-YOLOv5-Model-to-Detect-Objec

**Comment by ChrisMaunder** [comment]
We've added a Training module

**Comment by jimmylavino** [comment]
I don't understand the training module interface.  Is there any documentation for where to place your annotated images, etc?
