### ISSUE TITLE
[question] linux version

### ISSUE THREAD

**Issue by bartlebi** [codeproject/CodeProject.AI-Server#55]
It's just a question.
Please explain is there a version for linux without docker? I can't figure it out. Can i use dev version only to recognize data from agentdvr? I have a problem with gpu passthrought in docker under proxmox so I would prefer a clean install option

**Comment by ChrisMaunder** [comment]
There is no native Linux version, unfortunately.

**Comment by douglasfl** [comment]
Hello,
in version 2.1.11 codeprojectai was working very well in docker with Google Coral.

However, in the latest version (2.2.4) it no longer works...

The error log follows:
`20:23:29:Module 'ObjectDetection (Coral)' 1.5.1 (ID: ObjectDetectionCoral)
20:23:29:Module Path:   /app/modules/ObjectDetectionCoral
20:23:29:AutoStart:     True
20:23:29:Queue:         objectdetection_queue
20:23:29:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
20:23:29:GPU:           Support enabled
20:23:29:Parallelism:   1
20:23:29:Accelerator:
20:23:29:Half Precis.:  enable
20:23:29:Runtime:       python39
20:23:29:Runtime Loc:   Local
20:23:29:FilePath:      objectdetection_coral_adapter.py
20:23:29:Pre installed: False
20:23:29:Start pause:   1 sec
20:23:29:LogVerbosity:
20:23:29:Valid:         True
20:23:29:Environment Variables
20:23:29:MODELS_DIR = %CURRENT_MODULE_PATH%/assets
20:23:29:MODEL_SIZE = Medium
20:23:29:
20:23:29:Started ObjectDetection (Coral) module
20:23:36:objectdetection_coral_adapter.py: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
20:23:36:objectdetection_coral_adapter.py: Edge TPU detected
20:23:36:objectdetection_coral_adapter.py: Timeout connecting to the server
20:23:58:ObjectDetection (Coral):  [RuntimeError] : Traceback (most recent call last):
  File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 88, in do_detection
    result = do_detect(opts, img, score_threshold)
  File "/app/modules/ObjectDetectionCoral/objectdetection_coral.py", line 191, in do_detect
    interpreter.invoke()
  File "/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 941, in invoke
    self._interpreter.Invoke()
RuntimeError: Encountered an unresolved custom op. Did you miss a custom op or delegate?Node number 11 (EdgeTpuDelegateForCustomOp) failed to invoke.
20:23:58:ObjectDetection (Coral): Rec'd request for ObjectDetection (Coral) command 'detect' (...57acc1) took 46ms
Logging level
`


Any solution?
