### ISSUE TITLE
python environment creation question

### ISSUE THREAD

**Issue by MaksymTymkovych** [codeproject/CodeProject.AI-Server#56]
Hello, thank you for a very interesting project.

When analyzing the project, namely the installation scripts, it is clear from the code that the Windows installation  uses Python from the archive (here - https://codeproject-ai.s3.ca-central-1.amazonaws.com/sense/installer/dev/python39.zip
). 

But this Python build is very special, it includes pip, venv, etc.

Can you explain how you managed to create such an python build? (What are the main steps in creating it).

Thank you!

**Comment by MaksymTymkovych** [comment]
Done.

**Comment by wyyyyyy123** [comment]
As for the specific Python build mentioned in the screenshot (python39.zlpfrom a specific Amazon S3 URL), it seems to be a customized version tailored for the project's needs. The creator of the build would have followed the above steps (or similar) to include pip and venv. However, without more detailed information, it's difficult to provide an exact recipe for creating an identical build.
In summary, creating a custom Python build with pip and venv involves acquiring the source code, configuring and compiling it with the appropriate options, testing the build, and documenting the process.

**Comment by MaksymTymkovych** [comment]
As I understand it, the following assembly is used https://winpython.github.io/

**Comment by ChrisMaunder** [comment]
The python download should be coming from bunny.net. There's nothing special about it: we just created a python virtual environment then zipped up the python files from there and use that as the download. It's original binaries from python.org itself
