### ISSUE TITLE
Error in Update FaceProcessing: Call failed.

### ISSUE THREAD

**Issue by topgun97** [codeproject/CodeProject.AI-Server#58]
I install CodeprojectAI v2.1.11 in docker.It works. But it cann't update or install new modules.It display "Error in Update FaceProcessing: Call failed." when i update . everything is OK Before CodeprojectAI

![192 168 31 220_32168_](https://github.com/codeproject/CodeProject.AI-Server/assets/29767704/5f323291-3559-4e2c-81a9-ac890ace789d)

Server status.
![192 168 31 220_32168_ (1)](https://github.com/codeproject/CodeProject.AI-Server/assets/29767704/a620bc97-44b2-4793-b07b-0ee144792bac)

Server logs.
13:08:50:Operating System: Linux (Linux 5.4.0-155-generic #172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023)
13:08:50:CPUs:             Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (Intel)
13:08:50:                  1 CPU x 4 cores. 4 logical processors (x64)
13:08:50:GPU:              NVIDIA P106-100 (6 GiB) (NVIDIA)
13:08:50:                  Driver: 535.98 CUDA: 12.2 (capable: 12.2) Compute: 6.1
13:08:50:System RAM:       8 GiB
13:08:50:Target:           Linux
13:08:50:BuildConfig:      Release
13:08:50:Execution Env:    Docker
13:08:50:Runtime Env:      Production
13:08:50:.NET framework:   .NET 7.0.10
13:08:50:App DataDir:      /etc/codeproject/ai
13:08:50:Video adapter info:
13:08:50:ROOT_PATH                 = /app
13:08:50:RUNTIMES_PATH             = /app/runtimes
13:08:50:PREINSTALLED_MODULES_PATH = /app/preinstalled-modules
13:08:50:MODULES_PATH              = /app/modules
13:08:50:PYTHON_PATH               = /bin/linux/%PYTHON_RUNTIME%/venv/bin/python3
13:08:50:Data Dir                  = /etc/codeproject/ai
13:08:51:Server version:   2.1.11-Beta
13:08:53:Overriding address(es) 'http://+:32168, http://+:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
13:08:55:
13:08:55:Module 'Optical Character Recognition' (ID: OCR)
13:08:55:Module Path:   /app/modules/OCR
13:08:55:AutoStart:     True
13:08:55:Queue:         ocr_queue
13:08:55:Platforms:     windows,linux,macos,macos-arm64
13:08:55:GPU:           Support enabled
13:08:55:Parallelism:   0
13:08:55:Accelerator:
13:08:55:Half Precis.:  enable
13:08:55:Runtime:       python38
13:08:55:Runtime Loc:   Local
13:08:55:FilePath:      OCR_adapter.py
13:08:55:Pre installed: False
13:08:55:Start pause:   1 sec
13:08:55:LogVerbosity:
13:08:55:Valid:         True
13:08:55:Environment Variables
13:08:55:
13:08:55:Started Optical Character Recognition module
13:08:56:
13:08:56:Module 'Face Processing' (ID: FaceProcessing)
13:08:56:Module Path:   /app/preinstalled-modules/FaceProcessing
13:08:56:AutoStart:     True
13:08:56:Queue:         faceprocessing_queue
13:08:56:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:08:56:GPU:           Support enabled
13:08:56:Parallelism:   0
13:08:56:Accelerator:
13:08:56:Half Precis.:  enable
13:08:56:Runtime:       python38
13:08:56:Runtime Loc:   Shared
13:08:56:FilePath:      intelligencelayer\face.py
13:08:56:Pre installed: True
13:08:56:Start pause:   1 sec
13:08:56:LogVerbosity:
13:08:56:Valid:         True
13:08:56:Environment Variables
13:08:56:APPDIR             = %CURRENT_MODULE_PATH%\intelligencelayer
13:08:56:DATA_DIR           = %DATA_DIR%
13:08:56:MODE               = Medium
13:08:56:MODELS_DIR         = %CURRENT_MODULE_PATH%\assets
13:08:56:PROFILE            = desktop_gpu
13:08:56:USE_CUDA           = false
13:08:56:YOLOv5_AUTOINSTALL = false
13:08:56:YOLOv5_VERBOSE     = false
13:08:56:
13:08:56:Started Face Processing module
13:08:57:
13:08:57:Module 'Scene Classification' (ID: SceneClassifier)
13:08:57:Module Path:   /app/modules/SceneClassifier
13:08:57:AutoStart:     True
13:08:57:Queue:         sceneclassifier_queue
13:08:57:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:08:57:GPU:           Support enabled
13:08:57:Parallelism:   1
13:08:57:Accelerator:
13:08:57:Half Precis.:  enable
13:08:57:Runtime:       python38
13:08:57:Runtime Loc:   Shared
13:08:57:FilePath:      scene_adapter.py
13:08:57:Pre installed: False
13:08:57:Start pause:   1 sec
13:08:57:LogVerbosity:
13:08:57:Valid:         True
13:08:57:Environment Variables
13:08:57:APPDIR     = %CURRENT_MODULE_PATH%
13:08:57:MODELS_DIR = %CURRENT_MODULE_PATH%\assets
13:08:57:USE_CUDA   = False
13:08:57:
13:08:57:Started Scene Classification module
13:08:58:
13:08:58:Module 'Object Detection (YOLOv5 6.2)' (ID: ObjectDetectionYolo)
13:08:58:Module Path:   /app/preinstalled-modules/ObjectDetectionYolo
13:08:58:AutoStart:     True
13:08:58:Queue:         objectdetection_queue
13:08:58:Platforms:     all
13:08:58:GPU:           Support enabled
13:08:58:Parallelism:   0
13:08:58:Accelerator:
13:08:58:Half Precis.:  enable
13:08:58:Runtime:       python38
13:08:58:Runtime Loc:   Shared
13:08:58:FilePath:      detect_adapter.py
13:08:58:Pre installed: True
13:08:58:Start pause:   1 sec
13:08:58:LogVerbosity:
13:08:58:Valid:         True
13:08:58:Environment Variables
13:08:58:APPDIR             = %CURRENT_MODULE_PATH%
13:08:58:CUSTOM_MODELS_DIR  = %CURRENT_MODULE_PATH%/custom-models
13:08:58:MODELS_DIR         = %CURRENT_MODULE_PATH%/assets
13:08:58:MODEL_SIZE         = Medium
13:08:58:USE_CUDA           = True
13:08:58:YOLOv5_AUTOINSTALL = false
13:08:58:YOLOv5_VERBOSE     = false
13:08:58:
13:08:58:Started Object Detection (YOLOv5 6.2) module
13:08:59:
13:08:59:Module 'Super Resolution' (ID: SuperResolution)
13:08:59:Module Path:   /app/modules/SuperResolution
13:08:59:AutoStart:     True
13:08:59:Queue:         superresolution_queue
13:08:59:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:08:59:GPU:           Support enabled
13:08:59:Parallelism:   1
13:08:59:Accelerator:
13:08:59:Half Precis.:  enable
13:08:59:Runtime:       python38
13:08:59:Runtime Loc:   Local
13:08:59:FilePath:      superres_adapter.py
13:08:59:Pre installed: False
13:08:59:Start pause:   0 sec
13:08:59:LogVerbosity:
13:08:59:Valid:         True
13:08:59:Environment Variables
13:08:59:PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = python
13:08:59:
13:08:59:Started Super Resolution module
13:08:59:
13:08:59:Module 'License Plate Reader' (ID: ALPR)
13:08:59:Module Path:   /app/modules/ALPR
13:08:59:AutoStart:     True
13:08:59:Queue:         alpr_queue
13:08:59:Platforms:     windows,linux,macos,macos-arm64
13:08:59:GPU:           Support enabled
13:08:59:Parallelism:   0
13:08:59:Accelerator:
13:08:59:Half Precis.:  enable
13:08:59:Runtime:       python38
13:08:59:Runtime Loc:   Local
13:08:59:FilePath:      ALPR_adapter.py
13:08:59:Pre installed: False
13:08:59:Start pause:   1 sec
13:08:59:LogVerbosity:
13:08:59:Valid:         True
13:08:59:Environment Variables
13:08:59:AUTO_PLATE_ROTATE            = True
13:08:59:OCR_OPTIMAL_CHARACTER_HEIGHT = 60
13:08:59:OCR_OPTIMAL_CHARACTER_WIDTH  = 36
13:08:59:OCR_OPTIMIZATION             = True
13:08:59:PLATE_CONFIDENCE             = 0.7
13:08:59:PLATE_RESCALE_FACTOR         = 2
13:08:59:PLATE_ROTATE_DEG             = 0
13:08:59:
13:08:59:Started License Plate Reader module
13:09:04:Server: This is the latest version
13:11:20:face.py: GPU in use: NVIDIA P106-100
13:34:30:Sending shutdown request to python3/SuperResolution
13:34:35:Module SuperResolution has shutdown
13:35:03:SuperResolution went quietly
13:39:06:
13:39:06:Module 'Super Resolution' (ID: SuperResolution)
13:39:06:Module Path:   /app/modules/SuperResolution
13:39:06:AutoStart:     True
13:39:06:Queue:         superresolution_queue
13:39:06:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:39:06:GPU:           Support enabled
13:39:06:Parallelism:   1
13:39:06:Accelerator:
13:39:06:Half Precis.:  enable
13:39:06:Runtime:       python38
13:39:06:Runtime Loc:   Local
13:39:06:FilePath:      superres_adapter.py
13:39:06:Pre installed: False
13:39:06:Start pause:   0 sec
13:39:06:LogVerbosity:
13:39:06:Valid:         True
13:39:06:Environment Variables
13:39:06:PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = python
13:39:06:
13:39:06:Started Super Resolution module
13:39:20:Sending shutdown request to python3/SuperResolution
13:39:30:Module SuperResolution has shutdown
13:39:36:
13:39:36:Module 'Super Resolution' (ID: SuperResolution)
13:39:36:Module Path:   /app/modules/SuperResolution
13:39:36:AutoStart:     True
13:39:36:Queue:         superresolution_queue
13:39:36:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:39:36:GPU:           Support enabled
13:39:36:Parallelism:   1
13:39:36:Accelerator:
13:39:36:Half Precis.:  enable
13:39:36:Runtime:       python38
13:39:36:Runtime Loc:   Local
13:39:36:FilePath:      superres_adapter.py
13:39:36:Pre installed: False
13:39:36:Start pause:   0 sec
13:39:36:LogVerbosity:
13:39:36:Valid:         True
13:39:36:Environment Variables
13:39:36:PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = python
13:39:36:
13:39:36:Started Super Resolution module
13:39:53:SuperResolution went quietly
13:39:53:
13:39:53:Module 'Super Resolution' (ID: SuperResolution)
13:39:53:Module Path:   /app/modules/SuperResolution
13:39:53:AutoStart:     True
13:39:53:Queue:         superresolution_queue
13:39:53:Platforms:     windows,linux,linux-arm64,macos,macos-arm64
13:39:53:GPU:           Support enabled
13:39:53:Parallelism:   1
13:39:53:Accelerator:
13:39:53:Half Precis.:  enable
13:39:53:Runtime:       python38
13:39:53:Runtime Loc:   Local
13:39:53:FilePath:      superres_adapter.py
13:39:53:Pre installed: False
13:39:53:Start pause:   0 sec
13:39:53:LogVerbosity:
13:39:53:Valid:         True
13:39:53:Environment Variables
13:39:53:PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = python
13:39:53:
13:39:53:Started Super Resolution module
14:36:47:Call failed

**Comment by zenxedo** [comment]
I can't update or uninstall so it's not possible to install in persistent storage.

**Comment by Plutoaurus** [comment]
Same issue here with all updates

**Comment by Plutoaurus** [comment]
Ma age to get it working

Install latest python module from Microsoft store
Then follow 
https://packaging.python.org/en/latest/tutorials/installing-packages/

The key command being
py -m venv <DIR>\Scripts\activate

If you can type pip into command prompt and it doesn't give a error then you should be good
