### ISSUE TITLE
I don't understand the training module interface. 

### ISSUE THREAD

**Issue by jimmylavino** [codeproject/CodeProject.AI-Server#62]
Is there any documentation for where to place your annotated images, etc?  It isn't clear how to use the GUI.

**Comment by AKHwyJunkie** [comment]
This probably isn't a good venue to ask this question.  The issues section of Github is primarily for bug reporting against a particular project.  I'd suggest you visit the CodeProject AI [forums here](https://www.codeproject.com/Feature/CodeProjectAI-Discussions.aspx).
