### ISSUE TITLE
AWS 403 error when downloading modules

### ISSUE THREAD

**Issue by lazynooblet** [codeproject/CodeProject.AI-Server#67]
I see [lots of comments regarding this issue on the website/forum](https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way?msg=5962054#xx5962054xx) but doesn't look like an issue has been opened.

When the client attempts to install a module, it receives a 403 forbidden from AWS.

`08:29:13:ObjectDetectionCoral: Installing module ObjectDetectionCoral                                
08:29:13:ObjectDetectionCoral: Installing python.= in C:\Program Files\CodeProject\AI\runtimes\bin\windows\python.=
08:29:16:ObjectDetectionCoral: Start-BitsTransfer : HTTP status 403: The client does not have sufficient access rights to the requested server object.
08:29:16:ObjectDetectionCoral: At line:1 char:1
08:29:16:ObjectDetectionCoral: + Start-BitsTransfer -Source 'https://codeproject-ai.s3.ca-central-1.am ...
08:29:16:ObjectDetectionCoral: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
08:29:16:ObjectDetectionCoral:     + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
08:29:16:ObjectDetectionCoral:     + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits 
08:29:16:ObjectDetectionCoral:    TransferCommand`

Windows, 64-bit, 2.1.11-Beta

**Comment by ChrisMaunder** [comment]
Fixed
