### ISSUE TITLE
ObjectDetectionCoral  not starting

### ISSUE THREAD

**Issue by Nonobis** [codeproject/CodeProject.AI-Server#68]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else
Docker

**Describe the bug**

When starting the "ObjectDetectionCoral "

04:00:54:Started ObjectDetection (Coral) module
04:00:54:objectdetection_coral_adapter.py: Traceback (most recent call last):
04:00:54:objectdetection_coral_adapter.py:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 9, in 
04:00:54:objectdetection_coral_adapter.py:     from request_data import RequestData
04:00:54:objectdetection_coral_adapter.py:   File "/app/modules/ObjectDetectionCoral/../../SDK/Python/request_data.py", line 7, in 
04:00:54:objectdetection_coral_adapter.py:     from PIL import Image
04:00:54:objectdetection_coral_adapter.py: ModuleNotFoundError: No module named 'PIL'
04:00:54:Module ObjectDetectionCoral has shutdown

**Expected behavior**
Trying to use this new model with my tpu

**Screenshots**

**Your System (please complete the following information):**

Server version:   2.2.4-Beta
Operating System: Linux (Linux 6.2.16-3-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z))
CPUs:             Intel(R) Pentium(R) CPU G4400T @ 2.90GHz (Intel)
                  1 CPU x 2 cores. 2 logical processors (x64)
System RAM:       8 GiB
Target:           Linux
BuildConfig:      Release
Execution Env:    Docker
Runtime Env:      Production
.NET framework:   .NET 7.0.11
Video adapter info:
System GPU info:
  GPU 3D Usage       0%
  GPU RAM Usage      0
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168

**Additional context**

LXC container on Proxmox Server
Installed on LXC container with Google Coral TPU (USB) working with Frigate

**Comment by ChrisMaunder** [comment]
Can you please try uninstalling and then reinstalling the Coral module? It looks like the Python Pillow package wasn't installed correctly/

**Comment by Nonobis** [comment]
yes no problem. :)

**Comment by Nonobis** [comment]
Got this in logs ...

08:13:35:ObjectDetectionCoral: No schemas installed
08:13:36:ObjectDetectionCoral: sh: 1: lsmod: not found
08:15:06:ObjectDetectionCoral: The command could not be loaded, possibly because:
08:15:06:ObjectDetectionCoral:   * You intended to execute a .NET application:
08:15:06:ObjectDetectionCoral:       The application '--version' does not exist.
08:15:06:ObjectDetectionCoral:   * You intended to execute a .NET SDK command:
08:15:06:ObjectDetectionCoral:       No .NET SDKs were found.
08:15:06:ObjectDetectionCoral: Download a .NET SDK:
08:15:06:ObjectDetectionCoral: https://aka.ms/dotnet/download
08:15:06:ObjectDetectionCoral: Learn about SDK resolution:
08:15:06:ObjectDetectionCoral: https://aka.ms/dotnet/sdk-not-found
08:18:03:ObjectDetectionCoral: WARNING: Target directory /app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/PIL already exists. Specify --upgrade to force replacement.
08:18:03:ObjectDetectionCoral: WARNING: Target directory /app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/Pillow.libs already exists. Specify --upgrade to force replacement.
08:18:03:ObjectDetectionCoral: WARNING: Target directory /app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/bin already exists. Specify --upgrade to force replacement.

**Comment by Nonobis** [comment]
More error in log

15:27:14:
15:27:14:Started Face Processing module
15:27:17:ObjectDetectionCoral: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.82 80]
15:27:17:ObjectDetectionCoral: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.82 80]
15:27:17:ObjectDetectionCoral: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
15:27:17:Module ObjectDetectionCoral installed successfully.
15:27:17:Module ObjectDetectionCoral not configured to AutoStart.
15:27:17:Installer exited with code 10

**Comment by Nonobis** [comment]
15:29:09:MODEL_SIZE = Medium
15:29:09:
15:29:09:Error trying to start ObjectDetection (Coral) (objectdetection_coral_adapter.py)
15:29:10:An error occurred trying to start process '/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/bin/python3' with working directory '/app/modules/ObjectDetectionCoral'. No such file or directory
15:29:10:   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module)
15:29:10:Please check the CodeProject.AI installation completed successfully

**Comment by SeanECP** [comment]
Curious to know if these errors persist with newer versions like 2.5.6

**Comment by ChrisMaunder** [comment]
Please try the latest 2.6.x version
