### ISSUE TITLE
Coral TPU “ Timeout connecting to the server” error

### ISSUE THREAD

**Issue by guycobb2** [codeproject/CodeProject.AI-Server#70]
**Area of Concern**
- [ ] Server
- [ x] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Am getting a “Timeout connecting to the server” error for the coral TPU module. The coral I’m using is the USB version. 

**Expected behavior**

**Screenshots**
Here’s a copy/paste of log files.

12:13:12:Attempting to start ObjectDetectionCoral with /app/modules/ObjectDetectionCoral/bin/linux/python39/venv/bin/python3 "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py"
12:13:12:LogVerbosity:
12:13:12:Valid:         True
12:13:12:Environment Variables
12:13:12:MODELS_DIR = %CURRENT_MODULE_PATH%/assets
12:13:12:MODEL_SIZE = Medium
12:13:12:
12:13:12:Started ObjectDetection (Coral) module
12:13:14:Server: This is the latest version
12:13:14:Current Version is 2.2.4-Beta
12:13:23:objectdetection_coral_adapter.py: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
12:13:23:objectdetection_coral_adapter.py: Edge TPU detected
12:13:23:objectdetection_coral_adapter.py: Timeout connecting to the server
12:13:23:objectdetection_coral_adapter.py: CPAI_MODULE_REQUIRED_MB not found. Setting to default 0
12:13:23:objectdetection_coral_adapter.py: NUM_THREADS not found. Setting to default 1
12:13:23:objectdetection_coral_adapter.py: MIN_CONFIDENCE not found. Setting to default 0.5
12:13:23:objectdetection_coral_adapter.py: MODULE_PATH:    /app/modules/ObjectDetectionCoral
12:13:23:objectdetection_coral_adapter.py: MODELS_DIR:     /app/modules/ObjectDetectionCoral/assets
12:13:23:objectdetection_coral_adapter.py: MODEL_SIZE:     medium
12:13:23:objectdetection_coral_adapter.py: CPU_MODEL_NAME: efficientdet_lite3_512_ptq.tflite
12:13:23:objectdetection_coral_adapter.py: TPU_MODEL_NAME: efficientdet_lite3_512_ptq_edgetpu.tflite
12:13:23:objectdetection_coral_adapter.py: Input details: {'name': 'serving_default_images:0', 'index': 0, 'shape': array([  1, 512, 512,   3], dtype=int32), 'shape_signature': array([  1, 512, 512,   3], dtype=int32), 'dtype': , 'quantization': (0.0078125, 127), 'quantization_parameters': {'scales': array([0.0078125], dtype=float32), 'zero_points': array([127], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
12:13:23:objectdetection_coral_adapter.py: Output details: {'name': 'StatefulPartitionedCall:31', 'index': 23, 'shape': array([ 1, 25,  4], dtype=int32), 'shape_signature': array([ 1, 25,  4], dtype=int32), 'dtype': , 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
12:13:23:objectdetection_coral_adapter.py: ObjectDetection (Coral) started.ObjectDetection (Coral): ObjectDetection (Coral) started.
12:13:23:ObjectDetection (Coral): ObjectDetection (Coral) started.
12:15:44:objectdetection_coral_adapter.py: F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
12:15:44:objectdetection_coral_adapter.py: has exited
12:15:44:Module ObjectDetectionCoral has shutdown

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.2.4-Beta
 - OS: Unraid
 - System RAM 32Gb
 - GPU: intel integrated
 - GPU RAM (if available)  [e.g. 4Gb]

**Additional context**

**Comment by laurentopia** [comment]
Same but in windows 11.
Reverted to 2.10 and all is fine now.

**Comment by guycobb2** [comment]
> Same but in windows 11.
> Reverted to 2.10 and all is fine now.

will have to see if I can roll back and see how it goes.

**Comment by ChrisMaunder** [comment]
>objectdetection_coral_adapter.py: F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]

This seems like a hardware / driver / Unraid issue. Unfortunately this isn't something we can help with

**Comment by guycobb2** [comment]
> > objectdetection_coral_adapter.py: F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
> 
> This seems like a hardware / driver / Unraid issue. Unfortunately this isn't something we can help with

i also encounter this issue when running CPAI via a windows 10 VM.  The coral is passed through, seen in device manager, etc.  As soon as I start the coral module in CPAI the usb coral disconnects from the W10 VM.  Upon stopping the coral module, the usb coral reappears.  Any thoughts on this?
