### ISSUE TITLE
What is the load balancing strategy?

### ISSUE THREAD

**Issue by laurentopia** [codeproject/CodeProject.AI-Server#73]
As a test I spun up a few object detection and it seems that CP-AI uses all of them regardless of past efficiency, meaning that yolo-cpu will be used even though yolo-GPU is available (and 3x faster). Is this a simple idle-first queue? Random?
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/26075468/c25da517-19fd-42e1-b32c-1411868cbb00)
Here we should see 3x more GPU yolo than CPU if scheduling prioritized speed.

**Comment by ChrisMaunder** [comment]
Each module polls the server to see if there are jobs available. It's first in, best dressed, since the server isn't pushing, the modules are polling / pulling.

**Comment by laurentopia** [comment]
Ok that explains what I'm seeing. I guess that's fine when all devices have roughly the same speed.
What happens in the case with multiple Coral TPU? They're cheap again on Mouser...
