### ISSUE TITLE
Offline Installer for devices with no internet

### ISSUE THREAD

**Issue by krousenick** [codeproject/CodeProject.AI-Server#76]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ X] Installer
- [ X] Runtime [e.g. Python3.7, .NET]
- [ X] Module packages [e.g. PyTorch)
- [ X] Something else

**Describe the bug**
Hello I have a Windows machine without internet access and I am looking to install. I am hoping for a way to have the installer check for local copies of the packages. 

**Expected behavior**
I am hoping for a way to have the installer check for local copies of the packages. Can an all in one offline installer be provided or download links for each add-on/supporting package with an option during installation to choose local packages. 

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.3.4
 - OS: Windows 10/11
 - System RAM [16Gb]
 - GPU (if available) [Quadro 2000P]
 - GPU RAM (if available)  [4Gb]

**Additional context**

**Comment by ChrisMaunder** [comment]
Unfortunately we don't offer offline installers. There are just too many variants for us to have every possibility wrapped in a self-contained downloadable package

**Comment by onlineapps-cloud** [comment]
here you can find offline version which i use for my purposes, ant that will install  components that i used in screenshot: https://github.com/codeproject/CodeProject.AI-Server/issues/89#issuecomment-2064816912
