### ISSUE TITLE
Incorrect training data

### ISSUE THREAD

**Issue by wilsotc** [codeproject/CodeProject.AI-Server#77]
**Area of Concern**

- [ ] Something else

**Describe the bug**
An image to train recognition of a person is using the wrong person.

**Expected behavior**
Images of the person to recognize should be exclusively that person.

**Screenshots**
n/a

**Your System (please complete the following information):**
n/a

**Additional context**
demos/TestData/Faces/scarlett-johanson-3.jpg is Kate Winslet not Scarlett Johanson
https://en.wikipedia.org/wiki/Kate_Winslet

**Comment by ChrisMaunder** [comment]
Well spotted. Thank you. Fixed in the next release
