### ISSUE TITLE
GPU image on dockerhub has not been updated in months whereas the other images were updated a 19 days ago.

### ISSUE THREAD

**Issue by nabheet** [codeproject/CodeProject.AI-Server#78]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
I cannot find a 2.3 version with the GPU tag on dockerhub. 

**Expected behavior**
I am hoping that all platforms should have their latest pointing to 2.3.4.

**Comment by AKHwyJunkie** [comment]
It appears there have been some different forks in the GPU versions to reflect CUDA 11 vs. 12, so your previous tag might need to be updated.  Documented a bit [here](https://www.codeproject.com/AI/docs/install/running_in_docker.html).  Both these run v2.3.2.

```
docker pull codeproject/ai-server:cuda11_7-2.3.2
docker pull codeproject/ai-server:cuda12_2-2.3.2
```
FWIW, I've followed this project for quite awhile now.  It's not been uncommon for the Docker version to fall behind the Windows version.  Hard to say their exact development cycle, but I do think they focus more on Windows based bug fixes and then eventually roll the various updates into the Docker deployment every few versions.  I've also seen the tags (and even the Docker Hub designation) change without much fanfare or notice.  Always good to check [here](https://hub.docker.com/r/codeproject/ai-server/tags) for current tags.

**Comment by nabheet** [comment]
Thanks! I did find the cuda versions later and forgot to update this issue. I am currently using the cuda 12 version 2.3.2 image. Looks like the 2.3.4 version is only available for rpi and arm64. It would be nice to have this version for other supported platforms too.

**Comment by AKHwyJunkie** [comment]
In case you hadn't noticed, Chris pushed v2.4.6 to the Docker repository today.  Requires manual tags.  Still figuring out how to use the new mesh feature and routing, but might be interesting to you since you wanted to get into v2.4.

**Comment by nabheet** [comment]
Thanks! giving it whirl now :smiley:

**Comment by nabheet** [comment]
This mesh stuff looks interesting!

**Comment by tylergibson** [comment]
Bumping to the top again - it’s been 6 months and now multiple releases behind cpu images.

**Comment by AKHwyJunkie** [comment]
> scratch that - re-read through the docs and see that gpu is now tagged under cuda tags - maybe a docs update and a note on dockerhub that the gpu tag is deprecated

One thing I've found quite helpful with this project is to review the [tags on Docker Hub](https://hub.docker.com/r/codeproject/ai-server/tags).  There's been minor differences between releases and changes in the tagging structure.  I suspect this will eventually even itself out, but Docker Hub always shows you latest releases and the appropriate tag to use to get the image you want.

**Comment by ChrisMaunder** [comment]
Docker images have all been updated. Please check tags
