### ISSUE TITLE
Yolo V8 unable to be downloaded

### ISSUE THREAD

**Issue by xantari** [codeproject/CodeProject.AI-Server#81]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

You can not install YoloV8 module. Logs indicate it doesn't exist at the below location and it never downloads.

19:16:39:Unable to download module 'ObjectDetectionYOLOv8' from https://www.codeproject.com/KB/articles/5348853/ObjectDetectionYOLOv8-1.0.zip. Error: No bytes downloaded

**Expected behavior**

Module should install without error.

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.3.4-Beta
 - OS: Windows 10
 - System RAM: 128GB
 - GPU (if available): RTX 3070
 - GPU RAM (if available) 8GB

**Additional context**

**Comment by SeanECP** [comment]
Is this still a problem in later versions? Like 2.5.6

**Comment by xantari** [comment]
Seems to be resolved now. Closing.
