### ISSUE TITLE
Can't start CodeProject.AI.Server - error message says to install .Net runtimes, but they are installed.

### ISSUE THREAD

**Issue by Godwottery** [codeproject/CodeProject.AI-Server#82]
**Area of Concern**
- [x] Runtime [e.g. Python3.7, .NET]

**Describe the bug**
Cannot start CodeProject.AI.Server, with an error message saying that Microsoft.NETCore.App framework can't be installed even though the runtimes are installed as is are the SDKs

**Expected behavior**
I expect to be able to start CodeProject.AI.Server as the prerequisites are installed.

**Screenshots**
C:\Program Files\CodeProject\AI\Server>CodeProject.AI.Server.exe
You must install or update .NET to run this application.

App: C:\Program Files\CodeProject\AI\Server\CodeProject.AI.Server.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: C:\Program Files\CodeProject\AI\Server\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=win10-x64

CHECK RUNTIMES
C:\Program Files\CodeProject\AI\Server>dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

CHECK SDKs as per https://github.com/codeproject/CodeProject.AI-Server/issues/50

C:\Program Files\CodeProject\AI\Server>dotnet --list-sdks
7.0.404 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]

**Your System (please complete the following information):**
 - CodeProject.AI Server version: CodeProject.AI-Server-win-x64-2.3.4
 - OS: Windows 11
 - System RAM [16GB]
 - GPU (if available) [Not available]
 - GPU RAM (if available)  [NA]

**Additional context**
Same problem shows up in the Event Viewer.

**Comment by ChrisMaunder** [comment]
Please try the latest 2.6 installer

**Comment by onlineapps-cloud** [comment]
look at here: https://github.com/codeproject/CodeProject.AI-Server/issues/89#issuecomment-2064816912
