### ISSUE TITLE
Any environment variable to enable/start mesh?

### ISSUE THREAD

**Issue by armond-avanes** [codeproject/CodeProject.AI-Server#86]
I'm running AI Server via docker on RPi-5 (rpi64), and I'm wondering if there is any environment variable to enable/start mesh? I couldn't find anything in the documentation.

I've automated the installation of AI Server and I don't want to do any extra configuration after starting the container.

**Comment by ChrisMaunder** [comment]
Not en environment var, but in the appsettings.json file set   MeshOptions.Enable
```
"MeshOptions": {
    "Enable": false,
```
