### ISSUE TITLE
Latest Ubuntu Version listed as 2.5.4 however installs 2.5.1-RC2

### ISSUE THREAD

**Issue by c-scoot** [codeproject/CodeProject.AI-Server#90]
**Area of Concern**
- [ X] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ X] Something else

**Describe the bug**
2.5.4 Ubuntu installer registers as 2.5.1-RC2 and prompts you to update to latest version

**Expected behavior**
2.5.4 to be installed 

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.5.4
 - OS: Ubuntu 22.04

**Additional context**

**Comment by ChrisMaunder** [comment]
This has been fixed
