### ISSUE TITLE
cannot run the client application 

### ISSUE THREAD

**Issue by deepakn1079** [codeproject/CodeProject.AI-Server#92]
I am running the code project.ai in docker.

The dashboard loads fine . However i cannot run the client application to see how the model works .

I tried accessing the http://localhost:32168/vision.html  ..but no luck ...cannot find page .

i also tried creating the html to consume the api , still no luck . i ve attached the screen grab ...am i missing something here.

![image](https://github.com/codeproject/CodeProject.AI-Server/assets/46796403/d0d2fa90-c178-4bf1-9470-1238f8dd20b8)

**Comment by matthewDDennis** [comment]
For your API calls, all calls are POSTs, not GETs
