### ISSUE TITLE
Will not even install

### ISSUE THREAD

**Issue by Tom-Sumner** [codeproject/CodeProject.AI-Server#95]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [x] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Run the latest installer on a Windows 11 machine and absolutely nothing happens, no files are installed anywhere and no server running.

**Expected behaviour**
Program Installs

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.5.6
 - OS: Windows 11
 - System RAM: 32GB
 - GPU: GTX 1070
 - GPU RAM: 24GB

**Additional context**
Also fails when BlueIris tries to start it.

**Comment by Brynyard** [comment]
Same here, there's quite explicitly mentioned in all the docs I can find that it should install at least some modules, and that the service should be able to at least limp into some action, but it fails to a) install anything but the server exe files and b) provide any error messages or feedback why/how/if to install any of the modules.

**Comment by Tom-Sumner** [comment]
> Same here, there's quite explicitly mentioned in all the docs I can find that it should install at least some modules, and that the service should be able to at least limp into some action, but it fails to a) install anything but the server exe files and b) provide any error messages or feedback why/how/if to install any of the modules.

I got absolutely nothing installed. no server files or anything. the installer ran fine and had no errors.

**Comment by ChrisMaunder** [comment]
Please try version 2.6.2

**Comment by onlineapps-cloud** [comment]
look at here: https://github.com/codeproject/CodeProject.AI-Server/issues/89#issuecomment-2064816912
